// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/exchangeaccount"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExchangeAccountCreate is the builder for creating a ExchangeAccount entity.
type ExchangeAccountCreate struct {
	config
	mutation *ExchangeAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExchangeAccountCreate) SetCreatedAt(v time.Time) *ExchangeAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableCreatedAt(v *time.Time) *ExchangeAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExchangeAccountCreate) SetUpdatedAt(v time.Time) *ExchangeAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableUpdatedAt(v *time.Time) *ExchangeAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ExchangeAccountCreate) SetDeletedAt(v time.Time) *ExchangeAccountCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableDeletedAt(v *time.Time) *ExchangeAccountCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ExchangeAccountCreate) SetCreatedBy(v uint32) *ExchangeAccountCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableCreatedBy(v *uint32) *ExchangeAccountCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ExchangeAccountCreate) SetUpdatedBy(v uint32) *ExchangeAccountCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableUpdatedBy(v *uint32) *ExchangeAccountCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *ExchangeAccountCreate) SetDeletedBy(v uint32) *ExchangeAccountCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableDeletedBy(v *uint32) *ExchangeAccountCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *ExchangeAccountCreate) SetNickname(v string) *ExchangeAccountCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetExchangeName sets the "exchange_name" field.
func (_c *ExchangeAccountCreate) SetExchangeName(v string) *ExchangeAccountCreate {
	_c.mutation.SetExchangeName(v)
	return _c
}

// SetOriginAccount sets the "origin_account" field.
func (_c *ExchangeAccountCreate) SetOriginAccount(v string) *ExchangeAccountCreate {
	_c.mutation.SetOriginAccount(v)
	return _c
}

// SetAPIKey sets the "api_key" field.
func (_c *ExchangeAccountCreate) SetAPIKey(v string) *ExchangeAccountCreate {
	_c.mutation.SetAPIKey(v)
	return _c
}

// SetSecretKey sets the "secret_key" field.
func (_c *ExchangeAccountCreate) SetSecretKey(v string) *ExchangeAccountCreate {
	_c.mutation.SetSecretKey(v)
	return _c
}

// SetPassKey sets the "pass_key" field.
func (_c *ExchangeAccountCreate) SetPassKey(v string) *ExchangeAccountCreate {
	_c.mutation.SetPassKey(v)
	return _c
}

// SetNillablePassKey sets the "pass_key" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillablePassKey(v *string) *ExchangeAccountCreate {
	if v != nil {
		_c.SetPassKey(*v)
	}
	return _c
}

// SetBrokerID sets the "broker_id" field.
func (_c *ExchangeAccountCreate) SetBrokerID(v string) *ExchangeAccountCreate {
	_c.mutation.SetBrokerID(v)
	return _c
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableBrokerID(v *string) *ExchangeAccountCreate {
	if v != nil {
		_c.SetBrokerID(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ExchangeAccountCreate) SetRemark(v string) *ExchangeAccountCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableRemark(v *string) *ExchangeAccountCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetServerIps sets the "server_ips" field.
func (_c *ExchangeAccountCreate) SetServerIps(v string) *ExchangeAccountCreate {
	_c.mutation.SetServerIps(v)
	return _c
}

// SetNillableServerIps sets the "server_ips" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableServerIps(v *string) *ExchangeAccountCreate {
	if v != nil {
		_c.SetServerIps(*v)
	}
	return _c
}

// SetSpecialReqLimit sets the "special_req_limit" field.
func (_c *ExchangeAccountCreate) SetSpecialReqLimit(v float64) *ExchangeAccountCreate {
	_c.mutation.SetSpecialReqLimit(v)
	return _c
}

// SetNillableSpecialReqLimit sets the "special_req_limit" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableSpecialReqLimit(v *float64) *ExchangeAccountCreate {
	if v != nil {
		_c.SetSpecialReqLimit(*v)
	}
	return _c
}

// SetAccountType sets the "account_type" field.
func (_c *ExchangeAccountCreate) SetAccountType(v int8) *ExchangeAccountCreate {
	_c.mutation.SetAccountType(v)
	return _c
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableAccountType(v *int8) *ExchangeAccountCreate {
	if v != nil {
		_c.SetAccountType(*v)
	}
	return _c
}

// SetApplyTime sets the "apply_time" field.
func (_c *ExchangeAccountCreate) SetApplyTime(v int64) *ExchangeAccountCreate {
	_c.mutation.SetApplyTime(v)
	return _c
}

// SetNillableApplyTime sets the "apply_time" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableApplyTime(v *int64) *ExchangeAccountCreate {
	if v != nil {
		_c.SetApplyTime(*v)
	}
	return _c
}

// SetIsCombined sets the "is_combined" field.
func (_c *ExchangeAccountCreate) SetIsCombined(v bool) *ExchangeAccountCreate {
	_c.mutation.SetIsCombined(v)
	return _c
}

// SetNillableIsCombined sets the "is_combined" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableIsCombined(v *bool) *ExchangeAccountCreate {
	if v != nil {
		_c.SetIsCombined(*v)
	}
	return _c
}

// SetIsMulti sets the "is_multi" field.
func (_c *ExchangeAccountCreate) SetIsMulti(v bool) *ExchangeAccountCreate {
	_c.mutation.SetIsMulti(v)
	return _c
}

// SetNillableIsMulti sets the "is_multi" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableIsMulti(v *bool) *ExchangeAccountCreate {
	if v != nil {
		_c.SetIsMulti(*v)
	}
	return _c
}

// SetCombinedID sets the "combined_id" field.
func (_c *ExchangeAccountCreate) SetCombinedID(v string) *ExchangeAccountCreate {
	_c.mutation.SetCombinedID(v)
	return _c
}

// SetNillableCombinedID sets the "combined_id" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableCombinedID(v *string) *ExchangeAccountCreate {
	if v != nil {
		_c.SetCombinedID(*v)
	}
	return _c
}

// SetMotherID sets the "mother_id" field.
func (_c *ExchangeAccountCreate) SetMotherID(v uint32) *ExchangeAccountCreate {
	_c.mutation.SetMotherID(v)
	return _c
}

// SetNillableMotherID sets the "mother_id" field if the given value is not nil.
func (_c *ExchangeAccountCreate) SetNillableMotherID(v *uint32) *ExchangeAccountCreate {
	if v != nil {
		_c.SetMotherID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExchangeAccountCreate) SetID(v uint32) *ExchangeAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ExchangeAccountMutation object of the builder.
func (_c *ExchangeAccountCreate) Mutation() *ExchangeAccountMutation {
	return _c.mutation
}

// Save creates the ExchangeAccount in the database.
func (_c *ExchangeAccountCreate) Save(ctx context.Context) (*ExchangeAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExchangeAccountCreate) SaveX(ctx context.Context) *ExchangeAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExchangeAccountCreate) defaults() {
	if _, ok := _c.mutation.PassKey(); !ok {
		v := exchangeaccount.DefaultPassKey
		_c.mutation.SetPassKey(v)
	}
	if _, ok := _c.mutation.BrokerID(); !ok {
		v := exchangeaccount.DefaultBrokerID
		_c.mutation.SetBrokerID(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := exchangeaccount.DefaultRemark
		_c.mutation.SetRemark(v)
	}
	if _, ok := _c.mutation.ServerIps(); !ok {
		v := exchangeaccount.DefaultServerIps
		_c.mutation.SetServerIps(v)
	}
	if _, ok := _c.mutation.SpecialReqLimit(); !ok {
		v := exchangeaccount.DefaultSpecialReqLimit
		_c.mutation.SetSpecialReqLimit(v)
	}
	if _, ok := _c.mutation.AccountType(); !ok {
		v := exchangeaccount.DefaultAccountType
		_c.mutation.SetAccountType(v)
	}
	if _, ok := _c.mutation.ApplyTime(); !ok {
		v := exchangeaccount.DefaultApplyTime
		_c.mutation.SetApplyTime(v)
	}
	if _, ok := _c.mutation.IsCombined(); !ok {
		v := exchangeaccount.DefaultIsCombined
		_c.mutation.SetIsCombined(v)
	}
	if _, ok := _c.mutation.IsMulti(); !ok {
		v := exchangeaccount.DefaultIsMulti
		_c.mutation.SetIsMulti(v)
	}
	if _, ok := _c.mutation.CombinedID(); !ok {
		v := exchangeaccount.DefaultCombinedID
		_c.mutation.SetCombinedID(v)
	}
	if _, ok := _c.mutation.MotherID(); !ok {
		v := exchangeaccount.DefaultMotherID
		_c.mutation.SetMotherID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExchangeAccountCreate) check() error {
	if _, ok := _c.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "ExchangeAccount.nickname"`)}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := exchangeaccount.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.nickname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExchangeName(); !ok {
		return &ValidationError{Name: "exchange_name", err: errors.New(`ent: missing required field "ExchangeAccount.exchange_name"`)}
	}
	if v, ok := _c.mutation.ExchangeName(); ok {
		if err := exchangeaccount.ExchangeNameValidator(v); err != nil {
			return &ValidationError{Name: "exchange_name", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.exchange_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginAccount(); !ok {
		return &ValidationError{Name: "origin_account", err: errors.New(`ent: missing required field "ExchangeAccount.origin_account"`)}
	}
	if v, ok := _c.mutation.OriginAccount(); ok {
		if err := exchangeaccount.OriginAccountValidator(v); err != nil {
			return &ValidationError{Name: "origin_account", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.origin_account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKey(); !ok {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required field "ExchangeAccount.api_key"`)}
	}
	if v, ok := _c.mutation.APIKey(); ok {
		if err := exchangeaccount.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.api_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecretKey(); !ok {
		return &ValidationError{Name: "secret_key", err: errors.New(`ent: missing required field "ExchangeAccount.secret_key"`)}
	}
	if v, ok := _c.mutation.SecretKey(); ok {
		if err := exchangeaccount.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.secret_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PassKey(); ok {
		if err := exchangeaccount.PassKeyValidator(v); err != nil {
			return &ValidationError{Name: "pass_key", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.pass_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BrokerID(); ok {
		if err := exchangeaccount.BrokerIDValidator(v); err != nil {
			return &ValidationError{Name: "broker_id", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.broker_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := exchangeaccount.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountType(); !ok {
		return &ValidationError{Name: "account_type", err: errors.New(`ent: missing required field "ExchangeAccount.account_type"`)}
	}
	if _, ok := _c.mutation.IsCombined(); !ok {
		return &ValidationError{Name: "is_combined", err: errors.New(`ent: missing required field "ExchangeAccount.is_combined"`)}
	}
	if _, ok := _c.mutation.IsMulti(); !ok {
		return &ValidationError{Name: "is_multi", err: errors.New(`ent: missing required field "ExchangeAccount.is_multi"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := exchangeaccount.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ExchangeAccountCreate) sqlSave(ctx context.Context) (*ExchangeAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExchangeAccountCreate) createSpec() (*ExchangeAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &ExchangeAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exchangeaccount.Table, sqlgraph.NewFieldSpec(exchangeaccount.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(exchangeaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(exchangeaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(exchangeaccount.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(exchangeaccount.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(exchangeaccount.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(exchangeaccount.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(exchangeaccount.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := _c.mutation.ExchangeName(); ok {
		_spec.SetField(exchangeaccount.FieldExchangeName, field.TypeString, value)
		_node.ExchangeName = value
	}
	if value, ok := _c.mutation.OriginAccount(); ok {
		_spec.SetField(exchangeaccount.FieldOriginAccount, field.TypeString, value)
		_node.OriginAccount = value
	}
	if value, ok := _c.mutation.APIKey(); ok {
		_spec.SetField(exchangeaccount.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := _c.mutation.SecretKey(); ok {
		_spec.SetField(exchangeaccount.FieldSecretKey, field.TypeString, value)
		_node.SecretKey = value
	}
	if value, ok := _c.mutation.PassKey(); ok {
		_spec.SetField(exchangeaccount.FieldPassKey, field.TypeString, value)
		_node.PassKey = &value
	}
	if value, ok := _c.mutation.BrokerID(); ok {
		_spec.SetField(exchangeaccount.FieldBrokerID, field.TypeString, value)
		_node.BrokerID = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(exchangeaccount.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.ServerIps(); ok {
		_spec.SetField(exchangeaccount.FieldServerIps, field.TypeString, value)
		_node.ServerIps = &value
	}
	if value, ok := _c.mutation.SpecialReqLimit(); ok {
		_spec.SetField(exchangeaccount.FieldSpecialReqLimit, field.TypeFloat64, value)
		_node.SpecialReqLimit = &value
	}
	if value, ok := _c.mutation.AccountType(); ok {
		_spec.SetField(exchangeaccount.FieldAccountType, field.TypeInt8, value)
		_node.AccountType = value
	}
	if value, ok := _c.mutation.ApplyTime(); ok {
		_spec.SetField(exchangeaccount.FieldApplyTime, field.TypeInt64, value)
		_node.ApplyTime = &value
	}
	if value, ok := _c.mutation.IsCombined(); ok {
		_spec.SetField(exchangeaccount.FieldIsCombined, field.TypeBool, value)
		_node.IsCombined = value
	}
	if value, ok := _c.mutation.IsMulti(); ok {
		_spec.SetField(exchangeaccount.FieldIsMulti, field.TypeBool, value)
		_node.IsMulti = value
	}
	if value, ok := _c.mutation.CombinedID(); ok {
		_spec.SetField(exchangeaccount.FieldCombinedID, field.TypeString, value)
		_node.CombinedID = &value
	}
	if value, ok := _c.mutation.MotherID(); ok {
		_spec.SetField(exchangeaccount.FieldMotherID, field.TypeUint32, value)
		_node.MotherID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExchangeAccount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExchangeAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExchangeAccountCreate) OnConflict(opts ...sql.ConflictOption) *ExchangeAccountUpsertOne {
	_c.conflict = opts
	return &ExchangeAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExchangeAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExchangeAccountCreate) OnConflictColumns(columns ...string) *ExchangeAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExchangeAccountUpsertOne{
		create: _c,
	}
}

type (
	// ExchangeAccountUpsertOne is the builder for "upsert"-ing
	//  one ExchangeAccount node.
	ExchangeAccountUpsertOne struct {
		create *ExchangeAccountCreate
	}

	// ExchangeAccountUpsert is the "OnConflict" setter.
	ExchangeAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ExchangeAccountUpsert) SetUpdatedAt(v time.Time) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateUpdatedAt() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ExchangeAccountUpsert) ClearUpdatedAt() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExchangeAccountUpsert) SetDeletedAt(v time.Time) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateDeletedAt() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExchangeAccountUpsert) ClearDeletedAt() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ExchangeAccountUpsert) SetCreatedBy(v uint32) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateCreatedBy() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ExchangeAccountUpsert) AddCreatedBy(v uint32) *ExchangeAccountUpsert {
	u.Add(exchangeaccount.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ExchangeAccountUpsert) ClearCreatedBy() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExchangeAccountUpsert) SetUpdatedBy(v uint32) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateUpdatedBy() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ExchangeAccountUpsert) AddUpdatedBy(v uint32) *ExchangeAccountUpsert {
	u.Add(exchangeaccount.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExchangeAccountUpsert) ClearUpdatedBy() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ExchangeAccountUpsert) SetDeletedBy(v uint32) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateDeletedBy() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ExchangeAccountUpsert) AddDeletedBy(v uint32) *ExchangeAccountUpsert {
	u.Add(exchangeaccount.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ExchangeAccountUpsert) ClearDeletedBy() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldDeletedBy)
	return u
}

// SetNickname sets the "nickname" field.
func (u *ExchangeAccountUpsert) SetNickname(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldNickname, v)
	return u
}

// UpdateNickname sets the "nickname" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateNickname() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldNickname)
	return u
}

// SetExchangeName sets the "exchange_name" field.
func (u *ExchangeAccountUpsert) SetExchangeName(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldExchangeName, v)
	return u
}

// UpdateExchangeName sets the "exchange_name" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateExchangeName() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldExchangeName)
	return u
}

// SetOriginAccount sets the "origin_account" field.
func (u *ExchangeAccountUpsert) SetOriginAccount(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldOriginAccount, v)
	return u
}

// UpdateOriginAccount sets the "origin_account" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateOriginAccount() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldOriginAccount)
	return u
}

// SetAPIKey sets the "api_key" field.
func (u *ExchangeAccountUpsert) SetAPIKey(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldAPIKey, v)
	return u
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateAPIKey() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldAPIKey)
	return u
}

// SetSecretKey sets the "secret_key" field.
func (u *ExchangeAccountUpsert) SetSecretKey(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldSecretKey, v)
	return u
}

// UpdateSecretKey sets the "secret_key" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateSecretKey() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldSecretKey)
	return u
}

// SetPassKey sets the "pass_key" field.
func (u *ExchangeAccountUpsert) SetPassKey(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldPassKey, v)
	return u
}

// UpdatePassKey sets the "pass_key" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdatePassKey() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldPassKey)
	return u
}

// ClearPassKey clears the value of the "pass_key" field.
func (u *ExchangeAccountUpsert) ClearPassKey() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldPassKey)
	return u
}

// SetBrokerID sets the "broker_id" field.
func (u *ExchangeAccountUpsert) SetBrokerID(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldBrokerID, v)
	return u
}

// UpdateBrokerID sets the "broker_id" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateBrokerID() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldBrokerID)
	return u
}

// ClearBrokerID clears the value of the "broker_id" field.
func (u *ExchangeAccountUpsert) ClearBrokerID() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldBrokerID)
	return u
}

// SetRemark sets the "remark" field.
func (u *ExchangeAccountUpsert) SetRemark(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateRemark() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *ExchangeAccountUpsert) ClearRemark() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldRemark)
	return u
}

// SetServerIps sets the "server_ips" field.
func (u *ExchangeAccountUpsert) SetServerIps(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldServerIps, v)
	return u
}

// UpdateServerIps sets the "server_ips" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateServerIps() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldServerIps)
	return u
}

// ClearServerIps clears the value of the "server_ips" field.
func (u *ExchangeAccountUpsert) ClearServerIps() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldServerIps)
	return u
}

// SetSpecialReqLimit sets the "special_req_limit" field.
func (u *ExchangeAccountUpsert) SetSpecialReqLimit(v float64) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldSpecialReqLimit, v)
	return u
}

// UpdateSpecialReqLimit sets the "special_req_limit" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateSpecialReqLimit() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldSpecialReqLimit)
	return u
}

// AddSpecialReqLimit adds v to the "special_req_limit" field.
func (u *ExchangeAccountUpsert) AddSpecialReqLimit(v float64) *ExchangeAccountUpsert {
	u.Add(exchangeaccount.FieldSpecialReqLimit, v)
	return u
}

// ClearSpecialReqLimit clears the value of the "special_req_limit" field.
func (u *ExchangeAccountUpsert) ClearSpecialReqLimit() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldSpecialReqLimit)
	return u
}

// SetAccountType sets the "account_type" field.
func (u *ExchangeAccountUpsert) SetAccountType(v int8) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldAccountType, v)
	return u
}

// UpdateAccountType sets the "account_type" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateAccountType() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldAccountType)
	return u
}

// AddAccountType adds v to the "account_type" field.
func (u *ExchangeAccountUpsert) AddAccountType(v int8) *ExchangeAccountUpsert {
	u.Add(exchangeaccount.FieldAccountType, v)
	return u
}

// SetApplyTime sets the "apply_time" field.
func (u *ExchangeAccountUpsert) SetApplyTime(v int64) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldApplyTime, v)
	return u
}

// UpdateApplyTime sets the "apply_time" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateApplyTime() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldApplyTime)
	return u
}

// AddApplyTime adds v to the "apply_time" field.
func (u *ExchangeAccountUpsert) AddApplyTime(v int64) *ExchangeAccountUpsert {
	u.Add(exchangeaccount.FieldApplyTime, v)
	return u
}

// ClearApplyTime clears the value of the "apply_time" field.
func (u *ExchangeAccountUpsert) ClearApplyTime() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldApplyTime)
	return u
}

// SetIsCombined sets the "is_combined" field.
func (u *ExchangeAccountUpsert) SetIsCombined(v bool) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldIsCombined, v)
	return u
}

// UpdateIsCombined sets the "is_combined" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateIsCombined() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldIsCombined)
	return u
}

// SetIsMulti sets the "is_multi" field.
func (u *ExchangeAccountUpsert) SetIsMulti(v bool) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldIsMulti, v)
	return u
}

// UpdateIsMulti sets the "is_multi" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateIsMulti() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldIsMulti)
	return u
}

// SetCombinedID sets the "combined_id" field.
func (u *ExchangeAccountUpsert) SetCombinedID(v string) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldCombinedID, v)
	return u
}

// UpdateCombinedID sets the "combined_id" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateCombinedID() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldCombinedID)
	return u
}

// ClearCombinedID clears the value of the "combined_id" field.
func (u *ExchangeAccountUpsert) ClearCombinedID() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldCombinedID)
	return u
}

// SetMotherID sets the "mother_id" field.
func (u *ExchangeAccountUpsert) SetMotherID(v uint32) *ExchangeAccountUpsert {
	u.Set(exchangeaccount.FieldMotherID, v)
	return u
}

// UpdateMotherID sets the "mother_id" field to the value that was provided on create.
func (u *ExchangeAccountUpsert) UpdateMotherID() *ExchangeAccountUpsert {
	u.SetExcluded(exchangeaccount.FieldMotherID)
	return u
}

// AddMotherID adds v to the "mother_id" field.
func (u *ExchangeAccountUpsert) AddMotherID(v uint32) *ExchangeAccountUpsert {
	u.Add(exchangeaccount.FieldMotherID, v)
	return u
}

// ClearMotherID clears the value of the "mother_id" field.
func (u *ExchangeAccountUpsert) ClearMotherID() *ExchangeAccountUpsert {
	u.SetNull(exchangeaccount.FieldMotherID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ExchangeAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exchangeaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExchangeAccountUpsertOne) UpdateNewValues() *ExchangeAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(exchangeaccount.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(exchangeaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExchangeAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExchangeAccountUpsertOne) Ignore() *ExchangeAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExchangeAccountUpsertOne) DoNothing() *ExchangeAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExchangeAccountCreate.OnConflict
// documentation for more info.
func (u *ExchangeAccountUpsertOne) Update(set func(*ExchangeAccountUpsert)) *ExchangeAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExchangeAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExchangeAccountUpsertOne) SetUpdatedAt(v time.Time) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateUpdatedAt() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ExchangeAccountUpsertOne) ClearUpdatedAt() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExchangeAccountUpsertOne) SetDeletedAt(v time.Time) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateDeletedAt() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExchangeAccountUpsertOne) ClearDeletedAt() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExchangeAccountUpsertOne) SetCreatedBy(v uint32) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ExchangeAccountUpsertOne) AddCreatedBy(v uint32) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateCreatedBy() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ExchangeAccountUpsertOne) ClearCreatedBy() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExchangeAccountUpsertOne) SetUpdatedBy(v uint32) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ExchangeAccountUpsertOne) AddUpdatedBy(v uint32) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateUpdatedBy() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExchangeAccountUpsertOne) ClearUpdatedBy() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ExchangeAccountUpsertOne) SetDeletedBy(v uint32) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ExchangeAccountUpsertOne) AddDeletedBy(v uint32) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateDeletedBy() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ExchangeAccountUpsertOne) ClearDeletedBy() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearDeletedBy()
	})
}

// SetNickname sets the "nickname" field.
func (u *ExchangeAccountUpsertOne) SetNickname(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetNickname(v)
	})
}

// UpdateNickname sets the "nickname" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateNickname() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateNickname()
	})
}

// SetExchangeName sets the "exchange_name" field.
func (u *ExchangeAccountUpsertOne) SetExchangeName(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetExchangeName(v)
	})
}

// UpdateExchangeName sets the "exchange_name" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateExchangeName() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateExchangeName()
	})
}

// SetOriginAccount sets the "origin_account" field.
func (u *ExchangeAccountUpsertOne) SetOriginAccount(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetOriginAccount(v)
	})
}

// UpdateOriginAccount sets the "origin_account" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateOriginAccount() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateOriginAccount()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *ExchangeAccountUpsertOne) SetAPIKey(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateAPIKey() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateAPIKey()
	})
}

// SetSecretKey sets the "secret_key" field.
func (u *ExchangeAccountUpsertOne) SetSecretKey(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetSecretKey(v)
	})
}

// UpdateSecretKey sets the "secret_key" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateSecretKey() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateSecretKey()
	})
}

// SetPassKey sets the "pass_key" field.
func (u *ExchangeAccountUpsertOne) SetPassKey(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetPassKey(v)
	})
}

// UpdatePassKey sets the "pass_key" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdatePassKey() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdatePassKey()
	})
}

// ClearPassKey clears the value of the "pass_key" field.
func (u *ExchangeAccountUpsertOne) ClearPassKey() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearPassKey()
	})
}

// SetBrokerID sets the "broker_id" field.
func (u *ExchangeAccountUpsertOne) SetBrokerID(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetBrokerID(v)
	})
}

// UpdateBrokerID sets the "broker_id" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateBrokerID() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateBrokerID()
	})
}

// ClearBrokerID clears the value of the "broker_id" field.
func (u *ExchangeAccountUpsertOne) ClearBrokerID() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearBrokerID()
	})
}

// SetRemark sets the "remark" field.
func (u *ExchangeAccountUpsertOne) SetRemark(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateRemark() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ExchangeAccountUpsertOne) ClearRemark() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearRemark()
	})
}

// SetServerIps sets the "server_ips" field.
func (u *ExchangeAccountUpsertOne) SetServerIps(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetServerIps(v)
	})
}

// UpdateServerIps sets the "server_ips" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateServerIps() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateServerIps()
	})
}

// ClearServerIps clears the value of the "server_ips" field.
func (u *ExchangeAccountUpsertOne) ClearServerIps() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearServerIps()
	})
}

// SetSpecialReqLimit sets the "special_req_limit" field.
func (u *ExchangeAccountUpsertOne) SetSpecialReqLimit(v float64) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetSpecialReqLimit(v)
	})
}

// AddSpecialReqLimit adds v to the "special_req_limit" field.
func (u *ExchangeAccountUpsertOne) AddSpecialReqLimit(v float64) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddSpecialReqLimit(v)
	})
}

// UpdateSpecialReqLimit sets the "special_req_limit" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateSpecialReqLimit() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateSpecialReqLimit()
	})
}

// ClearSpecialReqLimit clears the value of the "special_req_limit" field.
func (u *ExchangeAccountUpsertOne) ClearSpecialReqLimit() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearSpecialReqLimit()
	})
}

// SetAccountType sets the "account_type" field.
func (u *ExchangeAccountUpsertOne) SetAccountType(v int8) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetAccountType(v)
	})
}

// AddAccountType adds v to the "account_type" field.
func (u *ExchangeAccountUpsertOne) AddAccountType(v int8) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddAccountType(v)
	})
}

// UpdateAccountType sets the "account_type" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateAccountType() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateAccountType()
	})
}

// SetApplyTime sets the "apply_time" field.
func (u *ExchangeAccountUpsertOne) SetApplyTime(v int64) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetApplyTime(v)
	})
}

// AddApplyTime adds v to the "apply_time" field.
func (u *ExchangeAccountUpsertOne) AddApplyTime(v int64) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddApplyTime(v)
	})
}

// UpdateApplyTime sets the "apply_time" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateApplyTime() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateApplyTime()
	})
}

// ClearApplyTime clears the value of the "apply_time" field.
func (u *ExchangeAccountUpsertOne) ClearApplyTime() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearApplyTime()
	})
}

// SetIsCombined sets the "is_combined" field.
func (u *ExchangeAccountUpsertOne) SetIsCombined(v bool) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetIsCombined(v)
	})
}

// UpdateIsCombined sets the "is_combined" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateIsCombined() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateIsCombined()
	})
}

// SetIsMulti sets the "is_multi" field.
func (u *ExchangeAccountUpsertOne) SetIsMulti(v bool) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetIsMulti(v)
	})
}

// UpdateIsMulti sets the "is_multi" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateIsMulti() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateIsMulti()
	})
}

// SetCombinedID sets the "combined_id" field.
func (u *ExchangeAccountUpsertOne) SetCombinedID(v string) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetCombinedID(v)
	})
}

// UpdateCombinedID sets the "combined_id" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateCombinedID() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateCombinedID()
	})
}

// ClearCombinedID clears the value of the "combined_id" field.
func (u *ExchangeAccountUpsertOne) ClearCombinedID() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearCombinedID()
	})
}

// SetMotherID sets the "mother_id" field.
func (u *ExchangeAccountUpsertOne) SetMotherID(v uint32) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetMotherID(v)
	})
}

// AddMotherID adds v to the "mother_id" field.
func (u *ExchangeAccountUpsertOne) AddMotherID(v uint32) *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddMotherID(v)
	})
}

// UpdateMotherID sets the "mother_id" field to the value that was provided on create.
func (u *ExchangeAccountUpsertOne) UpdateMotherID() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateMotherID()
	})
}

// ClearMotherID clears the value of the "mother_id" field.
func (u *ExchangeAccountUpsertOne) ClearMotherID() *ExchangeAccountUpsertOne {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearMotherID()
	})
}

// Exec executes the query.
func (u *ExchangeAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExchangeAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExchangeAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExchangeAccountUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExchangeAccountUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExchangeAccountCreateBulk is the builder for creating many ExchangeAccount entities in bulk.
type ExchangeAccountCreateBulk struct {
	config
	err      error
	builders []*ExchangeAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the ExchangeAccount entities in the database.
func (_c *ExchangeAccountCreateBulk) Save(ctx context.Context) ([]*ExchangeAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExchangeAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExchangeAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExchangeAccountCreateBulk) SaveX(ctx context.Context) []*ExchangeAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExchangeAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExchangeAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExchangeAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExchangeAccountUpsertBulk {
	_c.conflict = opts
	return &ExchangeAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExchangeAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExchangeAccountCreateBulk) OnConflictColumns(columns ...string) *ExchangeAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExchangeAccountUpsertBulk{
		create: _c,
	}
}

// ExchangeAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of ExchangeAccount nodes.
type ExchangeAccountUpsertBulk struct {
	create *ExchangeAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExchangeAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exchangeaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExchangeAccountUpsertBulk) UpdateNewValues() *ExchangeAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(exchangeaccount.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(exchangeaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExchangeAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExchangeAccountUpsertBulk) Ignore() *ExchangeAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExchangeAccountUpsertBulk) DoNothing() *ExchangeAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExchangeAccountCreateBulk.OnConflict
// documentation for more info.
func (u *ExchangeAccountUpsertBulk) Update(set func(*ExchangeAccountUpsert)) *ExchangeAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExchangeAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExchangeAccountUpsertBulk) SetUpdatedAt(v time.Time) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateUpdatedAt() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ExchangeAccountUpsertBulk) ClearUpdatedAt() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExchangeAccountUpsertBulk) SetDeletedAt(v time.Time) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateDeletedAt() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExchangeAccountUpsertBulk) ClearDeletedAt() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExchangeAccountUpsertBulk) SetCreatedBy(v uint32) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ExchangeAccountUpsertBulk) AddCreatedBy(v uint32) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateCreatedBy() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ExchangeAccountUpsertBulk) ClearCreatedBy() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExchangeAccountUpsertBulk) SetUpdatedBy(v uint32) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ExchangeAccountUpsertBulk) AddUpdatedBy(v uint32) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateUpdatedBy() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExchangeAccountUpsertBulk) ClearUpdatedBy() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ExchangeAccountUpsertBulk) SetDeletedBy(v uint32) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ExchangeAccountUpsertBulk) AddDeletedBy(v uint32) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateDeletedBy() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ExchangeAccountUpsertBulk) ClearDeletedBy() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearDeletedBy()
	})
}

// SetNickname sets the "nickname" field.
func (u *ExchangeAccountUpsertBulk) SetNickname(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetNickname(v)
	})
}

// UpdateNickname sets the "nickname" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateNickname() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateNickname()
	})
}

// SetExchangeName sets the "exchange_name" field.
func (u *ExchangeAccountUpsertBulk) SetExchangeName(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetExchangeName(v)
	})
}

// UpdateExchangeName sets the "exchange_name" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateExchangeName() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateExchangeName()
	})
}

// SetOriginAccount sets the "origin_account" field.
func (u *ExchangeAccountUpsertBulk) SetOriginAccount(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetOriginAccount(v)
	})
}

// UpdateOriginAccount sets the "origin_account" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateOriginAccount() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateOriginAccount()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *ExchangeAccountUpsertBulk) SetAPIKey(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateAPIKey() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateAPIKey()
	})
}

// SetSecretKey sets the "secret_key" field.
func (u *ExchangeAccountUpsertBulk) SetSecretKey(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetSecretKey(v)
	})
}

// UpdateSecretKey sets the "secret_key" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateSecretKey() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateSecretKey()
	})
}

// SetPassKey sets the "pass_key" field.
func (u *ExchangeAccountUpsertBulk) SetPassKey(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetPassKey(v)
	})
}

// UpdatePassKey sets the "pass_key" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdatePassKey() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdatePassKey()
	})
}

// ClearPassKey clears the value of the "pass_key" field.
func (u *ExchangeAccountUpsertBulk) ClearPassKey() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearPassKey()
	})
}

// SetBrokerID sets the "broker_id" field.
func (u *ExchangeAccountUpsertBulk) SetBrokerID(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetBrokerID(v)
	})
}

// UpdateBrokerID sets the "broker_id" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateBrokerID() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateBrokerID()
	})
}

// ClearBrokerID clears the value of the "broker_id" field.
func (u *ExchangeAccountUpsertBulk) ClearBrokerID() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearBrokerID()
	})
}

// SetRemark sets the "remark" field.
func (u *ExchangeAccountUpsertBulk) SetRemark(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateRemark() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ExchangeAccountUpsertBulk) ClearRemark() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearRemark()
	})
}

// SetServerIps sets the "server_ips" field.
func (u *ExchangeAccountUpsertBulk) SetServerIps(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetServerIps(v)
	})
}

// UpdateServerIps sets the "server_ips" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateServerIps() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateServerIps()
	})
}

// ClearServerIps clears the value of the "server_ips" field.
func (u *ExchangeAccountUpsertBulk) ClearServerIps() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearServerIps()
	})
}

// SetSpecialReqLimit sets the "special_req_limit" field.
func (u *ExchangeAccountUpsertBulk) SetSpecialReqLimit(v float64) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetSpecialReqLimit(v)
	})
}

// AddSpecialReqLimit adds v to the "special_req_limit" field.
func (u *ExchangeAccountUpsertBulk) AddSpecialReqLimit(v float64) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddSpecialReqLimit(v)
	})
}

// UpdateSpecialReqLimit sets the "special_req_limit" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateSpecialReqLimit() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateSpecialReqLimit()
	})
}

// ClearSpecialReqLimit clears the value of the "special_req_limit" field.
func (u *ExchangeAccountUpsertBulk) ClearSpecialReqLimit() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearSpecialReqLimit()
	})
}

// SetAccountType sets the "account_type" field.
func (u *ExchangeAccountUpsertBulk) SetAccountType(v int8) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetAccountType(v)
	})
}

// AddAccountType adds v to the "account_type" field.
func (u *ExchangeAccountUpsertBulk) AddAccountType(v int8) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddAccountType(v)
	})
}

// UpdateAccountType sets the "account_type" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateAccountType() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateAccountType()
	})
}

// SetApplyTime sets the "apply_time" field.
func (u *ExchangeAccountUpsertBulk) SetApplyTime(v int64) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetApplyTime(v)
	})
}

// AddApplyTime adds v to the "apply_time" field.
func (u *ExchangeAccountUpsertBulk) AddApplyTime(v int64) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddApplyTime(v)
	})
}

// UpdateApplyTime sets the "apply_time" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateApplyTime() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateApplyTime()
	})
}

// ClearApplyTime clears the value of the "apply_time" field.
func (u *ExchangeAccountUpsertBulk) ClearApplyTime() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearApplyTime()
	})
}

// SetIsCombined sets the "is_combined" field.
func (u *ExchangeAccountUpsertBulk) SetIsCombined(v bool) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetIsCombined(v)
	})
}

// UpdateIsCombined sets the "is_combined" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateIsCombined() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateIsCombined()
	})
}

// SetIsMulti sets the "is_multi" field.
func (u *ExchangeAccountUpsertBulk) SetIsMulti(v bool) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetIsMulti(v)
	})
}

// UpdateIsMulti sets the "is_multi" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateIsMulti() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateIsMulti()
	})
}

// SetCombinedID sets the "combined_id" field.
func (u *ExchangeAccountUpsertBulk) SetCombinedID(v string) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetCombinedID(v)
	})
}

// UpdateCombinedID sets the "combined_id" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateCombinedID() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateCombinedID()
	})
}

// ClearCombinedID clears the value of the "combined_id" field.
func (u *ExchangeAccountUpsertBulk) ClearCombinedID() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearCombinedID()
	})
}

// SetMotherID sets the "mother_id" field.
func (u *ExchangeAccountUpsertBulk) SetMotherID(v uint32) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.SetMotherID(v)
	})
}

// AddMotherID adds v to the "mother_id" field.
func (u *ExchangeAccountUpsertBulk) AddMotherID(v uint32) *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.AddMotherID(v)
	})
}

// UpdateMotherID sets the "mother_id" field to the value that was provided on create.
func (u *ExchangeAccountUpsertBulk) UpdateMotherID() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.UpdateMotherID()
	})
}

// ClearMotherID clears the value of the "mother_id" field.
func (u *ExchangeAccountUpsertBulk) ClearMotherID() *ExchangeAccountUpsertBulk {
	return u.Update(func(s *ExchangeAccountUpsert) {
		s.ClearMotherID()
	})
}

// Exec executes the query.
func (u *ExchangeAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExchangeAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExchangeAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExchangeAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
