// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/exchangeaccount"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExchangeAccountUpdate is the builder for updating ExchangeAccount entities.
type ExchangeAccountUpdate struct {
	config
	hooks     []Hook
	mutation  *ExchangeAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ExchangeAccountUpdate builder.
func (_u *ExchangeAccountUpdate) Where(ps ...predicate.ExchangeAccount) *ExchangeAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExchangeAccountUpdate) SetUpdatedAt(v time.Time) *ExchangeAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableUpdatedAt(v *time.Time) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ExchangeAccountUpdate) ClearUpdatedAt() *ExchangeAccountUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ExchangeAccountUpdate) SetDeletedAt(v time.Time) *ExchangeAccountUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableDeletedAt(v *time.Time) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ExchangeAccountUpdate) ClearDeletedAt() *ExchangeAccountUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ExchangeAccountUpdate) SetCreatedBy(v uint32) *ExchangeAccountUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableCreatedBy(v *uint32) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ExchangeAccountUpdate) AddCreatedBy(v int32) *ExchangeAccountUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ExchangeAccountUpdate) ClearCreatedBy() *ExchangeAccountUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ExchangeAccountUpdate) SetUpdatedBy(v uint32) *ExchangeAccountUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableUpdatedBy(v *uint32) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ExchangeAccountUpdate) AddUpdatedBy(v int32) *ExchangeAccountUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ExchangeAccountUpdate) ClearUpdatedBy() *ExchangeAccountUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ExchangeAccountUpdate) SetDeletedBy(v uint32) *ExchangeAccountUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableDeletedBy(v *uint32) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ExchangeAccountUpdate) AddDeletedBy(v int32) *ExchangeAccountUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ExchangeAccountUpdate) ClearDeletedBy() *ExchangeAccountUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *ExchangeAccountUpdate) SetNickname(v string) *ExchangeAccountUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableNickname(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetExchangeName sets the "exchange_name" field.
func (_u *ExchangeAccountUpdate) SetExchangeName(v string) *ExchangeAccountUpdate {
	_u.mutation.SetExchangeName(v)
	return _u
}

// SetNillableExchangeName sets the "exchange_name" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableExchangeName(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetExchangeName(*v)
	}
	return _u
}

// SetOriginAccount sets the "origin_account" field.
func (_u *ExchangeAccountUpdate) SetOriginAccount(v string) *ExchangeAccountUpdate {
	_u.mutation.SetOriginAccount(v)
	return _u
}

// SetNillableOriginAccount sets the "origin_account" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableOriginAccount(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetOriginAccount(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *ExchangeAccountUpdate) SetAPIKey(v string) *ExchangeAccountUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableAPIKey(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetSecretKey sets the "secret_key" field.
func (_u *ExchangeAccountUpdate) SetSecretKey(v string) *ExchangeAccountUpdate {
	_u.mutation.SetSecretKey(v)
	return _u
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableSecretKey(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetSecretKey(*v)
	}
	return _u
}

// SetPassKey sets the "pass_key" field.
func (_u *ExchangeAccountUpdate) SetPassKey(v string) *ExchangeAccountUpdate {
	_u.mutation.SetPassKey(v)
	return _u
}

// SetNillablePassKey sets the "pass_key" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillablePassKey(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetPassKey(*v)
	}
	return _u
}

// ClearPassKey clears the value of the "pass_key" field.
func (_u *ExchangeAccountUpdate) ClearPassKey() *ExchangeAccountUpdate {
	_u.mutation.ClearPassKey()
	return _u
}

// SetBrokerID sets the "broker_id" field.
func (_u *ExchangeAccountUpdate) SetBrokerID(v string) *ExchangeAccountUpdate {
	_u.mutation.SetBrokerID(v)
	return _u
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableBrokerID(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetBrokerID(*v)
	}
	return _u
}

// ClearBrokerID clears the value of the "broker_id" field.
func (_u *ExchangeAccountUpdate) ClearBrokerID() *ExchangeAccountUpdate {
	_u.mutation.ClearBrokerID()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ExchangeAccountUpdate) SetRemark(v string) *ExchangeAccountUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableRemark(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ExchangeAccountUpdate) ClearRemark() *ExchangeAccountUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetServerIps sets the "server_ips" field.
func (_u *ExchangeAccountUpdate) SetServerIps(v string) *ExchangeAccountUpdate {
	_u.mutation.SetServerIps(v)
	return _u
}

// SetNillableServerIps sets the "server_ips" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableServerIps(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetServerIps(*v)
	}
	return _u
}

// ClearServerIps clears the value of the "server_ips" field.
func (_u *ExchangeAccountUpdate) ClearServerIps() *ExchangeAccountUpdate {
	_u.mutation.ClearServerIps()
	return _u
}

// SetSpecialReqLimit sets the "special_req_limit" field.
func (_u *ExchangeAccountUpdate) SetSpecialReqLimit(v float64) *ExchangeAccountUpdate {
	_u.mutation.ResetSpecialReqLimit()
	_u.mutation.SetSpecialReqLimit(v)
	return _u
}

// SetNillableSpecialReqLimit sets the "special_req_limit" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableSpecialReqLimit(v *float64) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetSpecialReqLimit(*v)
	}
	return _u
}

// AddSpecialReqLimit adds value to the "special_req_limit" field.
func (_u *ExchangeAccountUpdate) AddSpecialReqLimit(v float64) *ExchangeAccountUpdate {
	_u.mutation.AddSpecialReqLimit(v)
	return _u
}

// ClearSpecialReqLimit clears the value of the "special_req_limit" field.
func (_u *ExchangeAccountUpdate) ClearSpecialReqLimit() *ExchangeAccountUpdate {
	_u.mutation.ClearSpecialReqLimit()
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *ExchangeAccountUpdate) SetAccountType(v int8) *ExchangeAccountUpdate {
	_u.mutation.ResetAccountType()
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableAccountType(v *int8) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// AddAccountType adds value to the "account_type" field.
func (_u *ExchangeAccountUpdate) AddAccountType(v int8) *ExchangeAccountUpdate {
	_u.mutation.AddAccountType(v)
	return _u
}

// SetApplyTime sets the "apply_time" field.
func (_u *ExchangeAccountUpdate) SetApplyTime(v int64) *ExchangeAccountUpdate {
	_u.mutation.ResetApplyTime()
	_u.mutation.SetApplyTime(v)
	return _u
}

// SetNillableApplyTime sets the "apply_time" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableApplyTime(v *int64) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetApplyTime(*v)
	}
	return _u
}

// AddApplyTime adds value to the "apply_time" field.
func (_u *ExchangeAccountUpdate) AddApplyTime(v int64) *ExchangeAccountUpdate {
	_u.mutation.AddApplyTime(v)
	return _u
}

// ClearApplyTime clears the value of the "apply_time" field.
func (_u *ExchangeAccountUpdate) ClearApplyTime() *ExchangeAccountUpdate {
	_u.mutation.ClearApplyTime()
	return _u
}

// SetIsCombined sets the "is_combined" field.
func (_u *ExchangeAccountUpdate) SetIsCombined(v bool) *ExchangeAccountUpdate {
	_u.mutation.SetIsCombined(v)
	return _u
}

// SetNillableIsCombined sets the "is_combined" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableIsCombined(v *bool) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetIsCombined(*v)
	}
	return _u
}

// SetIsMulti sets the "is_multi" field.
func (_u *ExchangeAccountUpdate) SetIsMulti(v bool) *ExchangeAccountUpdate {
	_u.mutation.SetIsMulti(v)
	return _u
}

// SetNillableIsMulti sets the "is_multi" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableIsMulti(v *bool) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetIsMulti(*v)
	}
	return _u
}

// SetCombinedID sets the "combined_id" field.
func (_u *ExchangeAccountUpdate) SetCombinedID(v string) *ExchangeAccountUpdate {
	_u.mutation.SetCombinedID(v)
	return _u
}

// SetNillableCombinedID sets the "combined_id" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableCombinedID(v *string) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetCombinedID(*v)
	}
	return _u
}

// ClearCombinedID clears the value of the "combined_id" field.
func (_u *ExchangeAccountUpdate) ClearCombinedID() *ExchangeAccountUpdate {
	_u.mutation.ClearCombinedID()
	return _u
}

// SetMotherID sets the "mother_id" field.
func (_u *ExchangeAccountUpdate) SetMotherID(v uint32) *ExchangeAccountUpdate {
	_u.mutation.ResetMotherID()
	_u.mutation.SetMotherID(v)
	return _u
}

// SetNillableMotherID sets the "mother_id" field if the given value is not nil.
func (_u *ExchangeAccountUpdate) SetNillableMotherID(v *uint32) *ExchangeAccountUpdate {
	if v != nil {
		_u.SetMotherID(*v)
	}
	return _u
}

// AddMotherID adds value to the "mother_id" field.
func (_u *ExchangeAccountUpdate) AddMotherID(v int32) *ExchangeAccountUpdate {
	_u.mutation.AddMotherID(v)
	return _u
}

// ClearMotherID clears the value of the "mother_id" field.
func (_u *ExchangeAccountUpdate) ClearMotherID() *ExchangeAccountUpdate {
	_u.mutation.ClearMotherID()
	return _u
}

// Mutation returns the ExchangeAccountMutation object of the builder.
func (_u *ExchangeAccountUpdate) Mutation() *ExchangeAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExchangeAccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExchangeAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExchangeAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExchangeAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExchangeAccountUpdate) check() error {
	if v, ok := _u.mutation.Nickname(); ok {
		if err := exchangeaccount.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.nickname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExchangeName(); ok {
		if err := exchangeaccount.ExchangeNameValidator(v); err != nil {
			return &ValidationError{Name: "exchange_name", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.exchange_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginAccount(); ok {
		if err := exchangeaccount.OriginAccountValidator(v); err != nil {
			return &ValidationError{Name: "origin_account", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.origin_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := exchangeaccount.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretKey(); ok {
		if err := exchangeaccount.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.secret_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PassKey(); ok {
		if err := exchangeaccount.PassKeyValidator(v); err != nil {
			return &ValidationError{Name: "pass_key", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.pass_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrokerID(); ok {
		if err := exchangeaccount.BrokerIDValidator(v); err != nil {
			return &ValidationError{Name: "broker_id", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.broker_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := exchangeaccount.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.remark": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ExchangeAccountUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ExchangeAccountUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ExchangeAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exchangeaccount.Table, exchangeaccount.Columns, sqlgraph.NewFieldSpec(exchangeaccount.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(exchangeaccount.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(exchangeaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(exchangeaccount.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(exchangeaccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(exchangeaccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(exchangeaccount.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(exchangeaccount.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(exchangeaccount.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(exchangeaccount.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(exchangeaccount.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(exchangeaccount.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(exchangeaccount.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(exchangeaccount.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(exchangeaccount.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(exchangeaccount.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExchangeName(); ok {
		_spec.SetField(exchangeaccount.FieldExchangeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginAccount(); ok {
		_spec.SetField(exchangeaccount.FieldOriginAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(exchangeaccount.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKey(); ok {
		_spec.SetField(exchangeaccount.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassKey(); ok {
		_spec.SetField(exchangeaccount.FieldPassKey, field.TypeString, value)
	}
	if _u.mutation.PassKeyCleared() {
		_spec.ClearField(exchangeaccount.FieldPassKey, field.TypeString)
	}
	if value, ok := _u.mutation.BrokerID(); ok {
		_spec.SetField(exchangeaccount.FieldBrokerID, field.TypeString, value)
	}
	if _u.mutation.BrokerIDCleared() {
		_spec.ClearField(exchangeaccount.FieldBrokerID, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(exchangeaccount.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(exchangeaccount.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.ServerIps(); ok {
		_spec.SetField(exchangeaccount.FieldServerIps, field.TypeString, value)
	}
	if _u.mutation.ServerIpsCleared() {
		_spec.ClearField(exchangeaccount.FieldServerIps, field.TypeString)
	}
	if value, ok := _u.mutation.SpecialReqLimit(); ok {
		_spec.SetField(exchangeaccount.FieldSpecialReqLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSpecialReqLimit(); ok {
		_spec.AddField(exchangeaccount.FieldSpecialReqLimit, field.TypeFloat64, value)
	}
	if _u.mutation.SpecialReqLimitCleared() {
		_spec.ClearField(exchangeaccount.FieldSpecialReqLimit, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(exchangeaccount.FieldAccountType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedAccountType(); ok {
		_spec.AddField(exchangeaccount.FieldAccountType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ApplyTime(); ok {
		_spec.SetField(exchangeaccount.FieldApplyTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApplyTime(); ok {
		_spec.AddField(exchangeaccount.FieldApplyTime, field.TypeInt64, value)
	}
	if _u.mutation.ApplyTimeCleared() {
		_spec.ClearField(exchangeaccount.FieldApplyTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.IsCombined(); ok {
		_spec.SetField(exchangeaccount.FieldIsCombined, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsMulti(); ok {
		_spec.SetField(exchangeaccount.FieldIsMulti, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CombinedID(); ok {
		_spec.SetField(exchangeaccount.FieldCombinedID, field.TypeString, value)
	}
	if _u.mutation.CombinedIDCleared() {
		_spec.ClearField(exchangeaccount.FieldCombinedID, field.TypeString)
	}
	if value, ok := _u.mutation.MotherID(); ok {
		_spec.SetField(exchangeaccount.FieldMotherID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedMotherID(); ok {
		_spec.AddField(exchangeaccount.FieldMotherID, field.TypeUint32, value)
	}
	if _u.mutation.MotherIDCleared() {
		_spec.ClearField(exchangeaccount.FieldMotherID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exchangeaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExchangeAccountUpdateOne is the builder for updating a single ExchangeAccount entity.
type ExchangeAccountUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ExchangeAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExchangeAccountUpdateOne) SetUpdatedAt(v time.Time) *ExchangeAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableUpdatedAt(v *time.Time) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ExchangeAccountUpdateOne) ClearUpdatedAt() *ExchangeAccountUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ExchangeAccountUpdateOne) SetDeletedAt(v time.Time) *ExchangeAccountUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableDeletedAt(v *time.Time) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ExchangeAccountUpdateOne) ClearDeletedAt() *ExchangeAccountUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ExchangeAccountUpdateOne) SetCreatedBy(v uint32) *ExchangeAccountUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableCreatedBy(v *uint32) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ExchangeAccountUpdateOne) AddCreatedBy(v int32) *ExchangeAccountUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ExchangeAccountUpdateOne) ClearCreatedBy() *ExchangeAccountUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ExchangeAccountUpdateOne) SetUpdatedBy(v uint32) *ExchangeAccountUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableUpdatedBy(v *uint32) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ExchangeAccountUpdateOne) AddUpdatedBy(v int32) *ExchangeAccountUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ExchangeAccountUpdateOne) ClearUpdatedBy() *ExchangeAccountUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ExchangeAccountUpdateOne) SetDeletedBy(v uint32) *ExchangeAccountUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableDeletedBy(v *uint32) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ExchangeAccountUpdateOne) AddDeletedBy(v int32) *ExchangeAccountUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ExchangeAccountUpdateOne) ClearDeletedBy() *ExchangeAccountUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *ExchangeAccountUpdateOne) SetNickname(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableNickname(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetExchangeName sets the "exchange_name" field.
func (_u *ExchangeAccountUpdateOne) SetExchangeName(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetExchangeName(v)
	return _u
}

// SetNillableExchangeName sets the "exchange_name" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableExchangeName(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetExchangeName(*v)
	}
	return _u
}

// SetOriginAccount sets the "origin_account" field.
func (_u *ExchangeAccountUpdateOne) SetOriginAccount(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetOriginAccount(v)
	return _u
}

// SetNillableOriginAccount sets the "origin_account" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableOriginAccount(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetOriginAccount(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *ExchangeAccountUpdateOne) SetAPIKey(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableAPIKey(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetSecretKey sets the "secret_key" field.
func (_u *ExchangeAccountUpdateOne) SetSecretKey(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetSecretKey(v)
	return _u
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableSecretKey(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetSecretKey(*v)
	}
	return _u
}

// SetPassKey sets the "pass_key" field.
func (_u *ExchangeAccountUpdateOne) SetPassKey(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetPassKey(v)
	return _u
}

// SetNillablePassKey sets the "pass_key" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillablePassKey(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetPassKey(*v)
	}
	return _u
}

// ClearPassKey clears the value of the "pass_key" field.
func (_u *ExchangeAccountUpdateOne) ClearPassKey() *ExchangeAccountUpdateOne {
	_u.mutation.ClearPassKey()
	return _u
}

// SetBrokerID sets the "broker_id" field.
func (_u *ExchangeAccountUpdateOne) SetBrokerID(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetBrokerID(v)
	return _u
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableBrokerID(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetBrokerID(*v)
	}
	return _u
}

// ClearBrokerID clears the value of the "broker_id" field.
func (_u *ExchangeAccountUpdateOne) ClearBrokerID() *ExchangeAccountUpdateOne {
	_u.mutation.ClearBrokerID()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ExchangeAccountUpdateOne) SetRemark(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableRemark(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ExchangeAccountUpdateOne) ClearRemark() *ExchangeAccountUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetServerIps sets the "server_ips" field.
func (_u *ExchangeAccountUpdateOne) SetServerIps(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetServerIps(v)
	return _u
}

// SetNillableServerIps sets the "server_ips" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableServerIps(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetServerIps(*v)
	}
	return _u
}

// ClearServerIps clears the value of the "server_ips" field.
func (_u *ExchangeAccountUpdateOne) ClearServerIps() *ExchangeAccountUpdateOne {
	_u.mutation.ClearServerIps()
	return _u
}

// SetSpecialReqLimit sets the "special_req_limit" field.
func (_u *ExchangeAccountUpdateOne) SetSpecialReqLimit(v float64) *ExchangeAccountUpdateOne {
	_u.mutation.ResetSpecialReqLimit()
	_u.mutation.SetSpecialReqLimit(v)
	return _u
}

// SetNillableSpecialReqLimit sets the "special_req_limit" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableSpecialReqLimit(v *float64) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetSpecialReqLimit(*v)
	}
	return _u
}

// AddSpecialReqLimit adds value to the "special_req_limit" field.
func (_u *ExchangeAccountUpdateOne) AddSpecialReqLimit(v float64) *ExchangeAccountUpdateOne {
	_u.mutation.AddSpecialReqLimit(v)
	return _u
}

// ClearSpecialReqLimit clears the value of the "special_req_limit" field.
func (_u *ExchangeAccountUpdateOne) ClearSpecialReqLimit() *ExchangeAccountUpdateOne {
	_u.mutation.ClearSpecialReqLimit()
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *ExchangeAccountUpdateOne) SetAccountType(v int8) *ExchangeAccountUpdateOne {
	_u.mutation.ResetAccountType()
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableAccountType(v *int8) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// AddAccountType adds value to the "account_type" field.
func (_u *ExchangeAccountUpdateOne) AddAccountType(v int8) *ExchangeAccountUpdateOne {
	_u.mutation.AddAccountType(v)
	return _u
}

// SetApplyTime sets the "apply_time" field.
func (_u *ExchangeAccountUpdateOne) SetApplyTime(v int64) *ExchangeAccountUpdateOne {
	_u.mutation.ResetApplyTime()
	_u.mutation.SetApplyTime(v)
	return _u
}

// SetNillableApplyTime sets the "apply_time" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableApplyTime(v *int64) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetApplyTime(*v)
	}
	return _u
}

// AddApplyTime adds value to the "apply_time" field.
func (_u *ExchangeAccountUpdateOne) AddApplyTime(v int64) *ExchangeAccountUpdateOne {
	_u.mutation.AddApplyTime(v)
	return _u
}

// ClearApplyTime clears the value of the "apply_time" field.
func (_u *ExchangeAccountUpdateOne) ClearApplyTime() *ExchangeAccountUpdateOne {
	_u.mutation.ClearApplyTime()
	return _u
}

// SetIsCombined sets the "is_combined" field.
func (_u *ExchangeAccountUpdateOne) SetIsCombined(v bool) *ExchangeAccountUpdateOne {
	_u.mutation.SetIsCombined(v)
	return _u
}

// SetNillableIsCombined sets the "is_combined" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableIsCombined(v *bool) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetIsCombined(*v)
	}
	return _u
}

// SetIsMulti sets the "is_multi" field.
func (_u *ExchangeAccountUpdateOne) SetIsMulti(v bool) *ExchangeAccountUpdateOne {
	_u.mutation.SetIsMulti(v)
	return _u
}

// SetNillableIsMulti sets the "is_multi" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableIsMulti(v *bool) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetIsMulti(*v)
	}
	return _u
}

// SetCombinedID sets the "combined_id" field.
func (_u *ExchangeAccountUpdateOne) SetCombinedID(v string) *ExchangeAccountUpdateOne {
	_u.mutation.SetCombinedID(v)
	return _u
}

// SetNillableCombinedID sets the "combined_id" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableCombinedID(v *string) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetCombinedID(*v)
	}
	return _u
}

// ClearCombinedID clears the value of the "combined_id" field.
func (_u *ExchangeAccountUpdateOne) ClearCombinedID() *ExchangeAccountUpdateOne {
	_u.mutation.ClearCombinedID()
	return _u
}

// SetMotherID sets the "mother_id" field.
func (_u *ExchangeAccountUpdateOne) SetMotherID(v uint32) *ExchangeAccountUpdateOne {
	_u.mutation.ResetMotherID()
	_u.mutation.SetMotherID(v)
	return _u
}

// SetNillableMotherID sets the "mother_id" field if the given value is not nil.
func (_u *ExchangeAccountUpdateOne) SetNillableMotherID(v *uint32) *ExchangeAccountUpdateOne {
	if v != nil {
		_u.SetMotherID(*v)
	}
	return _u
}

// AddMotherID adds value to the "mother_id" field.
func (_u *ExchangeAccountUpdateOne) AddMotherID(v int32) *ExchangeAccountUpdateOne {
	_u.mutation.AddMotherID(v)
	return _u
}

// ClearMotherID clears the value of the "mother_id" field.
func (_u *ExchangeAccountUpdateOne) ClearMotherID() *ExchangeAccountUpdateOne {
	_u.mutation.ClearMotherID()
	return _u
}

// Mutation returns the ExchangeAccountMutation object of the builder.
func (_u *ExchangeAccountUpdateOne) Mutation() *ExchangeAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExchangeAccountUpdate builder.
func (_u *ExchangeAccountUpdateOne) Where(ps ...predicate.ExchangeAccount) *ExchangeAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExchangeAccountUpdateOne) Select(field string, fields ...string) *ExchangeAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExchangeAccount entity.
func (_u *ExchangeAccountUpdateOne) Save(ctx context.Context) (*ExchangeAccount, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExchangeAccountUpdateOne) SaveX(ctx context.Context) *ExchangeAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExchangeAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExchangeAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExchangeAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Nickname(); ok {
		if err := exchangeaccount.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.nickname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExchangeName(); ok {
		if err := exchangeaccount.ExchangeNameValidator(v); err != nil {
			return &ValidationError{Name: "exchange_name", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.exchange_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginAccount(); ok {
		if err := exchangeaccount.OriginAccountValidator(v); err != nil {
			return &ValidationError{Name: "origin_account", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.origin_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := exchangeaccount.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretKey(); ok {
		if err := exchangeaccount.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.secret_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PassKey(); ok {
		if err := exchangeaccount.PassKeyValidator(v); err != nil {
			return &ValidationError{Name: "pass_key", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.pass_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrokerID(); ok {
		if err := exchangeaccount.BrokerIDValidator(v); err != nil {
			return &ValidationError{Name: "broker_id", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.broker_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := exchangeaccount.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "ExchangeAccount.remark": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ExchangeAccountUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ExchangeAccountUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ExchangeAccountUpdateOne) sqlSave(ctx context.Context) (_node *ExchangeAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exchangeaccount.Table, exchangeaccount.Columns, sqlgraph.NewFieldSpec(exchangeaccount.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExchangeAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exchangeaccount.FieldID)
		for _, f := range fields {
			if !exchangeaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exchangeaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(exchangeaccount.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(exchangeaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(exchangeaccount.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(exchangeaccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(exchangeaccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(exchangeaccount.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(exchangeaccount.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(exchangeaccount.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(exchangeaccount.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(exchangeaccount.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(exchangeaccount.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(exchangeaccount.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(exchangeaccount.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(exchangeaccount.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(exchangeaccount.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExchangeName(); ok {
		_spec.SetField(exchangeaccount.FieldExchangeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginAccount(); ok {
		_spec.SetField(exchangeaccount.FieldOriginAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(exchangeaccount.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKey(); ok {
		_spec.SetField(exchangeaccount.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassKey(); ok {
		_spec.SetField(exchangeaccount.FieldPassKey, field.TypeString, value)
	}
	if _u.mutation.PassKeyCleared() {
		_spec.ClearField(exchangeaccount.FieldPassKey, field.TypeString)
	}
	if value, ok := _u.mutation.BrokerID(); ok {
		_spec.SetField(exchangeaccount.FieldBrokerID, field.TypeString, value)
	}
	if _u.mutation.BrokerIDCleared() {
		_spec.ClearField(exchangeaccount.FieldBrokerID, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(exchangeaccount.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(exchangeaccount.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.ServerIps(); ok {
		_spec.SetField(exchangeaccount.FieldServerIps, field.TypeString, value)
	}
	if _u.mutation.ServerIpsCleared() {
		_spec.ClearField(exchangeaccount.FieldServerIps, field.TypeString)
	}
	if value, ok := _u.mutation.SpecialReqLimit(); ok {
		_spec.SetField(exchangeaccount.FieldSpecialReqLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSpecialReqLimit(); ok {
		_spec.AddField(exchangeaccount.FieldSpecialReqLimit, field.TypeFloat64, value)
	}
	if _u.mutation.SpecialReqLimitCleared() {
		_spec.ClearField(exchangeaccount.FieldSpecialReqLimit, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(exchangeaccount.FieldAccountType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedAccountType(); ok {
		_spec.AddField(exchangeaccount.FieldAccountType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ApplyTime(); ok {
		_spec.SetField(exchangeaccount.FieldApplyTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApplyTime(); ok {
		_spec.AddField(exchangeaccount.FieldApplyTime, field.TypeInt64, value)
	}
	if _u.mutation.ApplyTimeCleared() {
		_spec.ClearField(exchangeaccount.FieldApplyTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.IsCombined(); ok {
		_spec.SetField(exchangeaccount.FieldIsCombined, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsMulti(); ok {
		_spec.SetField(exchangeaccount.FieldIsMulti, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CombinedID(); ok {
		_spec.SetField(exchangeaccount.FieldCombinedID, field.TypeString, value)
	}
	if _u.mutation.CombinedIDCleared() {
		_spec.ClearField(exchangeaccount.FieldCombinedID, field.TypeString)
	}
	if value, ok := _u.mutation.MotherID(); ok {
		_spec.SetField(exchangeaccount.FieldMotherID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedMotherID(); ok {
		_spec.AddField(exchangeaccount.FieldMotherID, field.TypeUint32, value)
	}
	if _u.mutation.MotherIDCleared() {
		_spec.ClearField(exchangeaccount.FieldMotherID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ExchangeAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exchangeaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
