// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"go-wind-admin/app/admin/service/internal/data/ent/robot"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RobotUpdate is the builder for updating Robot entities.
type RobotUpdate struct {
	config
	hooks     []Hook
	mutation  *RobotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RobotUpdate builder.
func (_u *RobotUpdate) Where(ps ...predicate.Robot) *RobotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RobotUpdate) SetCreatedBy(v uint32) *RobotUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableCreatedBy(v *uint32) *RobotUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RobotUpdate) AddCreatedBy(v int32) *RobotUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *RobotUpdate) ClearCreatedBy() *RobotUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RobotUpdate) SetUpdatedBy(v uint32) *RobotUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableUpdatedBy(v *uint32) *RobotUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *RobotUpdate) AddUpdatedBy(v int32) *RobotUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *RobotUpdate) ClearUpdatedBy() *RobotUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *RobotUpdate) SetDeletedBy(v uint32) *RobotUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableDeletedBy(v *uint32) *RobotUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *RobotUpdate) AddDeletedBy(v int32) *RobotUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *RobotUpdate) ClearDeletedBy() *RobotUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RobotUpdate) SetUpdatedAt(v time.Time) *RobotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableUpdatedAt(v *time.Time) *RobotUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RobotUpdate) ClearUpdatedAt() *RobotUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RobotUpdate) SetDeletedAt(v time.Time) *RobotUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableDeletedAt(v *time.Time) *RobotUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RobotUpdate) ClearDeletedAt() *RobotUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *RobotUpdate) SetRemark(v string) *RobotUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableRemark(v *string) *RobotUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *RobotUpdate) ClearRemark() *RobotUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *RobotUpdate) SetNickname(v string) *RobotUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableNickname(v *string) *RobotUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// ClearNickname clears the value of the "nickname" field.
func (_u *RobotUpdate) ClearNickname() *RobotUpdate {
	_u.mutation.ClearNickname()
	return _u
}

// SetExchange sets the "exchange" field.
func (_u *RobotUpdate) SetExchange(v string) *RobotUpdate {
	_u.mutation.SetExchange(v)
	return _u
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableExchange(v *string) *RobotUpdate {
	if v != nil {
		_u.SetExchange(*v)
	}
	return _u
}

// ClearExchange clears the value of the "exchange" field.
func (_u *RobotUpdate) ClearExchange() *RobotUpdate {
	_u.mutation.ClearExchange()
	return _u
}

// SetVersion sets the "version" field.
func (_u *RobotUpdate) SetVersion(v string) *RobotUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableVersion(v *string) *RobotUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *RobotUpdate) ClearVersion() *RobotUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RobotUpdate) SetStatus(v string) *RobotUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableStatus(v *string) *RobotUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *RobotUpdate) ClearStatus() *RobotUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *RobotUpdate) SetBalance(v float64) *RobotUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableBalance(v *float64) *RobotUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *RobotUpdate) AddBalance(v float64) *RobotUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetInitBalance sets the "init_balance" field.
func (_u *RobotUpdate) SetInitBalance(v float64) *RobotUpdate {
	_u.mutation.ResetInitBalance()
	_u.mutation.SetInitBalance(v)
	return _u
}

// SetNillableInitBalance sets the "init_balance" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableInitBalance(v *float64) *RobotUpdate {
	if v != nil {
		_u.SetInitBalance(*v)
	}
	return _u
}

// AddInitBalance adds value to the "init_balance" field.
func (_u *RobotUpdate) AddInitBalance(v float64) *RobotUpdate {
	_u.mutation.AddInitBalance(v)
	return _u
}

// SetRegisteredAt sets the "registered_at" field.
func (_u *RobotUpdate) SetRegisteredAt(v time.Time) *RobotUpdate {
	_u.mutation.SetRegisteredAt(v)
	return _u
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableRegisteredAt(v *time.Time) *RobotUpdate {
	if v != nil {
		_u.SetRegisteredAt(*v)
	}
	return _u
}

// ClearRegisteredAt clears the value of the "registered_at" field.
func (_u *RobotUpdate) ClearRegisteredAt() *RobotUpdate {
	_u.mutation.ClearRegisteredAt()
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *RobotUpdate) SetLastHeartbeat(v time.Time) *RobotUpdate {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableLastHeartbeat(v *time.Time) *RobotUpdate {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (_u *RobotUpdate) ClearLastHeartbeat() *RobotUpdate {
	_u.mutation.ClearLastHeartbeat()
	return _u
}

// SetServerID sets the "server_id" field.
func (_u *RobotUpdate) SetServerID(v uint32) *RobotUpdate {
	_u.mutation.ResetServerID()
	_u.mutation.SetServerID(v)
	return _u
}

// SetNillableServerID sets the "server_id" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableServerID(v *uint32) *RobotUpdate {
	if v != nil {
		_u.SetServerID(*v)
	}
	return _u
}

// AddServerID adds value to the "server_id" field.
func (_u *RobotUpdate) AddServerID(v int32) *RobotUpdate {
	_u.mutation.AddServerID(v)
	return _u
}

// ClearServerID clears the value of the "server_id" field.
func (_u *RobotUpdate) ClearServerID() *RobotUpdate {
	_u.mutation.ClearServerID()
	return _u
}

// SetExchangeAccountID sets the "exchange_account_id" field.
func (_u *RobotUpdate) SetExchangeAccountID(v uint32) *RobotUpdate {
	_u.mutation.ResetExchangeAccountID()
	_u.mutation.SetExchangeAccountID(v)
	return _u
}

// SetNillableExchangeAccountID sets the "exchange_account_id" field if the given value is not nil.
func (_u *RobotUpdate) SetNillableExchangeAccountID(v *uint32) *RobotUpdate {
	if v != nil {
		_u.SetExchangeAccountID(*v)
	}
	return _u
}

// AddExchangeAccountID adds value to the "exchange_account_id" field.
func (_u *RobotUpdate) AddExchangeAccountID(v int32) *RobotUpdate {
	_u.mutation.AddExchangeAccountID(v)
	return _u
}

// ClearExchangeAccountID clears the value of the "exchange_account_id" field.
func (_u *RobotUpdate) ClearExchangeAccountID() *RobotUpdate {
	_u.mutation.ClearExchangeAccountID()
	return _u
}

// Mutation returns the RobotMutation object of the builder.
func (_u *RobotUpdate) Mutation() *RobotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RobotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RobotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RobotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RobotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RobotUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RobotUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RobotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(robot.Table, robot.Columns, sqlgraph.NewFieldSpec(robot.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(robot.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(robot.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(robot.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(robot.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(robot.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(robot.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(robot.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(robot.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(robot.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(robot.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(robot.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(robot.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(robot.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(robot.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(robot.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(robot.FieldRemark, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(robot.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(robot.FieldNickname, field.TypeString, value)
	}
	if _u.mutation.NicknameCleared() {
		_spec.ClearField(robot.FieldNickname, field.TypeString)
	}
	if value, ok := _u.mutation.Exchange(); ok {
		_spec.SetField(robot.FieldExchange, field.TypeString, value)
	}
	if _u.mutation.ExchangeCleared() {
		_spec.ClearField(robot.FieldExchange, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(robot.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(robot.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(robot.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(robot.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(robot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(robot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InitBalance(); ok {
		_spec.SetField(robot.FieldInitBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInitBalance(); ok {
		_spec.AddField(robot.FieldInitBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RegisteredAt(); ok {
		_spec.SetField(robot.FieldRegisteredAt, field.TypeTime, value)
	}
	if _u.mutation.RegisteredAtCleared() {
		_spec.ClearField(robot.FieldRegisteredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(robot.FieldLastHeartbeat, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatCleared() {
		_spec.ClearField(robot.FieldLastHeartbeat, field.TypeTime)
	}
	if value, ok := _u.mutation.ServerID(); ok {
		_spec.SetField(robot.FieldServerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedServerID(); ok {
		_spec.AddField(robot.FieldServerID, field.TypeUint32, value)
	}
	if _u.mutation.ServerIDCleared() {
		_spec.ClearField(robot.FieldServerID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ExchangeAccountID(); ok {
		_spec.SetField(robot.FieldExchangeAccountID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedExchangeAccountID(); ok {
		_spec.AddField(robot.FieldExchangeAccountID, field.TypeUint32, value)
	}
	if _u.mutation.ExchangeAccountIDCleared() {
		_spec.ClearField(robot.FieldExchangeAccountID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{robot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RobotUpdateOne is the builder for updating a single Robot entity.
type RobotUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RobotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedBy sets the "created_by" field.
func (_u *RobotUpdateOne) SetCreatedBy(v uint32) *RobotUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableCreatedBy(v *uint32) *RobotUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RobotUpdateOne) AddCreatedBy(v int32) *RobotUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *RobotUpdateOne) ClearCreatedBy() *RobotUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RobotUpdateOne) SetUpdatedBy(v uint32) *RobotUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableUpdatedBy(v *uint32) *RobotUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *RobotUpdateOne) AddUpdatedBy(v int32) *RobotUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *RobotUpdateOne) ClearUpdatedBy() *RobotUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *RobotUpdateOne) SetDeletedBy(v uint32) *RobotUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableDeletedBy(v *uint32) *RobotUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *RobotUpdateOne) AddDeletedBy(v int32) *RobotUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *RobotUpdateOne) ClearDeletedBy() *RobotUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RobotUpdateOne) SetUpdatedAt(v time.Time) *RobotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableUpdatedAt(v *time.Time) *RobotUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RobotUpdateOne) ClearUpdatedAt() *RobotUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RobotUpdateOne) SetDeletedAt(v time.Time) *RobotUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableDeletedAt(v *time.Time) *RobotUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RobotUpdateOne) ClearDeletedAt() *RobotUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *RobotUpdateOne) SetRemark(v string) *RobotUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableRemark(v *string) *RobotUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *RobotUpdateOne) ClearRemark() *RobotUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *RobotUpdateOne) SetNickname(v string) *RobotUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableNickname(v *string) *RobotUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// ClearNickname clears the value of the "nickname" field.
func (_u *RobotUpdateOne) ClearNickname() *RobotUpdateOne {
	_u.mutation.ClearNickname()
	return _u
}

// SetExchange sets the "exchange" field.
func (_u *RobotUpdateOne) SetExchange(v string) *RobotUpdateOne {
	_u.mutation.SetExchange(v)
	return _u
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableExchange(v *string) *RobotUpdateOne {
	if v != nil {
		_u.SetExchange(*v)
	}
	return _u
}

// ClearExchange clears the value of the "exchange" field.
func (_u *RobotUpdateOne) ClearExchange() *RobotUpdateOne {
	_u.mutation.ClearExchange()
	return _u
}

// SetVersion sets the "version" field.
func (_u *RobotUpdateOne) SetVersion(v string) *RobotUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableVersion(v *string) *RobotUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *RobotUpdateOne) ClearVersion() *RobotUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RobotUpdateOne) SetStatus(v string) *RobotUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableStatus(v *string) *RobotUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *RobotUpdateOne) ClearStatus() *RobotUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *RobotUpdateOne) SetBalance(v float64) *RobotUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableBalance(v *float64) *RobotUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *RobotUpdateOne) AddBalance(v float64) *RobotUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetInitBalance sets the "init_balance" field.
func (_u *RobotUpdateOne) SetInitBalance(v float64) *RobotUpdateOne {
	_u.mutation.ResetInitBalance()
	_u.mutation.SetInitBalance(v)
	return _u
}

// SetNillableInitBalance sets the "init_balance" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableInitBalance(v *float64) *RobotUpdateOne {
	if v != nil {
		_u.SetInitBalance(*v)
	}
	return _u
}

// AddInitBalance adds value to the "init_balance" field.
func (_u *RobotUpdateOne) AddInitBalance(v float64) *RobotUpdateOne {
	_u.mutation.AddInitBalance(v)
	return _u
}

// SetRegisteredAt sets the "registered_at" field.
func (_u *RobotUpdateOne) SetRegisteredAt(v time.Time) *RobotUpdateOne {
	_u.mutation.SetRegisteredAt(v)
	return _u
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableRegisteredAt(v *time.Time) *RobotUpdateOne {
	if v != nil {
		_u.SetRegisteredAt(*v)
	}
	return _u
}

// ClearRegisteredAt clears the value of the "registered_at" field.
func (_u *RobotUpdateOne) ClearRegisteredAt() *RobotUpdateOne {
	_u.mutation.ClearRegisteredAt()
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *RobotUpdateOne) SetLastHeartbeat(v time.Time) *RobotUpdateOne {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableLastHeartbeat(v *time.Time) *RobotUpdateOne {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (_u *RobotUpdateOne) ClearLastHeartbeat() *RobotUpdateOne {
	_u.mutation.ClearLastHeartbeat()
	return _u
}

// SetServerID sets the "server_id" field.
func (_u *RobotUpdateOne) SetServerID(v uint32) *RobotUpdateOne {
	_u.mutation.ResetServerID()
	_u.mutation.SetServerID(v)
	return _u
}

// SetNillableServerID sets the "server_id" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableServerID(v *uint32) *RobotUpdateOne {
	if v != nil {
		_u.SetServerID(*v)
	}
	return _u
}

// AddServerID adds value to the "server_id" field.
func (_u *RobotUpdateOne) AddServerID(v int32) *RobotUpdateOne {
	_u.mutation.AddServerID(v)
	return _u
}

// ClearServerID clears the value of the "server_id" field.
func (_u *RobotUpdateOne) ClearServerID() *RobotUpdateOne {
	_u.mutation.ClearServerID()
	return _u
}

// SetExchangeAccountID sets the "exchange_account_id" field.
func (_u *RobotUpdateOne) SetExchangeAccountID(v uint32) *RobotUpdateOne {
	_u.mutation.ResetExchangeAccountID()
	_u.mutation.SetExchangeAccountID(v)
	return _u
}

// SetNillableExchangeAccountID sets the "exchange_account_id" field if the given value is not nil.
func (_u *RobotUpdateOne) SetNillableExchangeAccountID(v *uint32) *RobotUpdateOne {
	if v != nil {
		_u.SetExchangeAccountID(*v)
	}
	return _u
}

// AddExchangeAccountID adds value to the "exchange_account_id" field.
func (_u *RobotUpdateOne) AddExchangeAccountID(v int32) *RobotUpdateOne {
	_u.mutation.AddExchangeAccountID(v)
	return _u
}

// ClearExchangeAccountID clears the value of the "exchange_account_id" field.
func (_u *RobotUpdateOne) ClearExchangeAccountID() *RobotUpdateOne {
	_u.mutation.ClearExchangeAccountID()
	return _u
}

// Mutation returns the RobotMutation object of the builder.
func (_u *RobotUpdateOne) Mutation() *RobotMutation {
	return _u.mutation
}

// Where appends a list predicates to the RobotUpdate builder.
func (_u *RobotUpdateOne) Where(ps ...predicate.Robot) *RobotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RobotUpdateOne) Select(field string, fields ...string) *RobotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Robot entity.
func (_u *RobotUpdateOne) Save(ctx context.Context) (*Robot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RobotUpdateOne) SaveX(ctx context.Context) *Robot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RobotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RobotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RobotUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RobotUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RobotUpdateOne) sqlSave(ctx context.Context) (_node *Robot, err error) {
	_spec := sqlgraph.NewUpdateSpec(robot.Table, robot.Columns, sqlgraph.NewFieldSpec(robot.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Robot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, robot.FieldID)
		for _, f := range fields {
			if !robot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != robot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(robot.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(robot.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(robot.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(robot.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(robot.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(robot.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(robot.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(robot.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(robot.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(robot.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(robot.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(robot.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(robot.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(robot.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(robot.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(robot.FieldRemark, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(robot.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(robot.FieldNickname, field.TypeString, value)
	}
	if _u.mutation.NicknameCleared() {
		_spec.ClearField(robot.FieldNickname, field.TypeString)
	}
	if value, ok := _u.mutation.Exchange(); ok {
		_spec.SetField(robot.FieldExchange, field.TypeString, value)
	}
	if _u.mutation.ExchangeCleared() {
		_spec.ClearField(robot.FieldExchange, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(robot.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(robot.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(robot.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(robot.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(robot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(robot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InitBalance(); ok {
		_spec.SetField(robot.FieldInitBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInitBalance(); ok {
		_spec.AddField(robot.FieldInitBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RegisteredAt(); ok {
		_spec.SetField(robot.FieldRegisteredAt, field.TypeTime, value)
	}
	if _u.mutation.RegisteredAtCleared() {
		_spec.ClearField(robot.FieldRegisteredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(robot.FieldLastHeartbeat, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatCleared() {
		_spec.ClearField(robot.FieldLastHeartbeat, field.TypeTime)
	}
	if value, ok := _u.mutation.ServerID(); ok {
		_spec.SetField(robot.FieldServerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedServerID(); ok {
		_spec.AddField(robot.FieldServerID, field.TypeUint32, value)
	}
	if _u.mutation.ServerIDCleared() {
		_spec.ClearField(robot.FieldServerID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ExchangeAccountID(); ok {
		_spec.SetField(robot.FieldExchangeAccountID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedExchangeAccountID(); ok {
		_spec.AddField(robot.FieldExchangeAccountID, field.TypeUint32, value)
	}
	if _u.mutation.ExchangeAccountIDCleared() {
		_spec.ClearField(robot.FieldExchangeAccountID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Robot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{robot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
