// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/robot"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RobotCreate is the builder for creating a Robot entity.
type RobotCreate struct {
	config
	mutation *RobotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedBy sets the "created_by" field.
func (_c *RobotCreate) SetCreatedBy(v uint32) *RobotCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *RobotCreate) SetNillableCreatedBy(v *uint32) *RobotCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *RobotCreate) SetUpdatedBy(v uint32) *RobotCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *RobotCreate) SetNillableUpdatedBy(v *uint32) *RobotCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *RobotCreate) SetDeletedBy(v uint32) *RobotCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *RobotCreate) SetNillableDeletedBy(v *uint32) *RobotCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RobotCreate) SetCreatedAt(v time.Time) *RobotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RobotCreate) SetNillableCreatedAt(v *time.Time) *RobotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RobotCreate) SetUpdatedAt(v time.Time) *RobotCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RobotCreate) SetNillableUpdatedAt(v *time.Time) *RobotCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *RobotCreate) SetDeletedAt(v time.Time) *RobotCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *RobotCreate) SetNillableDeletedAt(v *time.Time) *RobotCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *RobotCreate) SetRemark(v string) *RobotCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *RobotCreate) SetNillableRemark(v *string) *RobotCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *RobotCreate) SetTenantID(v uint32) *RobotCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *RobotCreate) SetNillableTenantID(v *uint32) *RobotCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetRid sets the "rid" field.
func (_c *RobotCreate) SetRid(v string) *RobotCreate {
	_c.mutation.SetRid(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RobotCreate) SetStatus(v uint) *RobotCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RobotCreate) SetNillableStatus(v *uint) *RobotCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *RobotCreate) SetBalance(v float64) *RobotCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *RobotCreate) SetNillableBalance(v *float64) *RobotCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RobotCreate) SetID(v uint32) *RobotCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RobotMutation object of the builder.
func (_c *RobotCreate) Mutation() *RobotMutation {
	return _c.mutation
}

// Save creates the Robot in the database.
func (_c *RobotCreate) Save(ctx context.Context) (*Robot, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RobotCreate) SaveX(ctx context.Context) *Robot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RobotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RobotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RobotCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := robot.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := robot.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Balance(); !ok {
		v := robot.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RobotCreate) check() error {
	if _, ok := _c.mutation.Rid(); !ok {
		return &ValidationError{Name: "rid", err: errors.New(`ent: missing required field "Robot.rid"`)}
	}
	if v, ok := _c.mutation.Rid(); ok {
		if err := robot.RidValidator(v); err != nil {
			return &ValidationError{Name: "rid", err: fmt.Errorf(`ent: validator failed for field "Robot.rid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Robot.status"`)}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "Robot.balance"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := robot.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Robot.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RobotCreate) sqlSave(ctx context.Context) (*Robot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RobotCreate) createSpec() (*Robot, *sqlgraph.CreateSpec) {
	var (
		_node = &Robot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(robot.Table, sqlgraph.NewFieldSpec(robot.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(robot.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(robot.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(robot.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(robot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(robot.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(robot.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(robot.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(robot.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Rid(); ok {
		_spec.SetField(robot.FieldRid, field.TypeString, value)
		_node.Rid = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(robot.FieldStatus, field.TypeUint, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(robot.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Robot.Create().
//		SetCreatedBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RobotUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *RobotCreate) OnConflict(opts ...sql.ConflictOption) *RobotUpsertOne {
	_c.conflict = opts
	return &RobotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Robot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RobotCreate) OnConflictColumns(columns ...string) *RobotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RobotUpsertOne{
		create: _c,
	}
}

type (
	// RobotUpsertOne is the builder for "upsert"-ing
	//  one Robot node.
	RobotUpsertOne struct {
		create *RobotCreate
	}

	// RobotUpsert is the "OnConflict" setter.
	RobotUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedBy sets the "created_by" field.
func (u *RobotUpsert) SetCreatedBy(v uint32) *RobotUpsert {
	u.Set(robot.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RobotUpsert) UpdateCreatedBy() *RobotUpsert {
	u.SetExcluded(robot.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RobotUpsert) AddCreatedBy(v uint32) *RobotUpsert {
	u.Add(robot.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *RobotUpsert) ClearCreatedBy() *RobotUpsert {
	u.SetNull(robot.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *RobotUpsert) SetUpdatedBy(v uint32) *RobotUpsert {
	u.Set(robot.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *RobotUpsert) UpdateUpdatedBy() *RobotUpsert {
	u.SetExcluded(robot.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *RobotUpsert) AddUpdatedBy(v uint32) *RobotUpsert {
	u.Add(robot.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *RobotUpsert) ClearUpdatedBy() *RobotUpsert {
	u.SetNull(robot.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *RobotUpsert) SetDeletedBy(v uint32) *RobotUpsert {
	u.Set(robot.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *RobotUpsert) UpdateDeletedBy() *RobotUpsert {
	u.SetExcluded(robot.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *RobotUpsert) AddDeletedBy(v uint32) *RobotUpsert {
	u.Add(robot.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *RobotUpsert) ClearDeletedBy() *RobotUpsert {
	u.SetNull(robot.FieldDeletedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RobotUpsert) SetUpdatedAt(v time.Time) *RobotUpsert {
	u.Set(robot.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RobotUpsert) UpdateUpdatedAt() *RobotUpsert {
	u.SetExcluded(robot.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *RobotUpsert) ClearUpdatedAt() *RobotUpsert {
	u.SetNull(robot.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RobotUpsert) SetDeletedAt(v time.Time) *RobotUpsert {
	u.Set(robot.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RobotUpsert) UpdateDeletedAt() *RobotUpsert {
	u.SetExcluded(robot.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RobotUpsert) ClearDeletedAt() *RobotUpsert {
	u.SetNull(robot.FieldDeletedAt)
	return u
}

// SetRemark sets the "remark" field.
func (u *RobotUpsert) SetRemark(v string) *RobotUpsert {
	u.Set(robot.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *RobotUpsert) UpdateRemark() *RobotUpsert {
	u.SetExcluded(robot.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *RobotUpsert) ClearRemark() *RobotUpsert {
	u.SetNull(robot.FieldRemark)
	return u
}

// SetStatus sets the "status" field.
func (u *RobotUpsert) SetStatus(v uint) *RobotUpsert {
	u.Set(robot.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RobotUpsert) UpdateStatus() *RobotUpsert {
	u.SetExcluded(robot.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *RobotUpsert) AddStatus(v uint) *RobotUpsert {
	u.Add(robot.FieldStatus, v)
	return u
}

// SetBalance sets the "balance" field.
func (u *RobotUpsert) SetBalance(v float64) *RobotUpsert {
	u.Set(robot.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *RobotUpsert) UpdateBalance() *RobotUpsert {
	u.SetExcluded(robot.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *RobotUpsert) AddBalance(v float64) *RobotUpsert {
	u.Add(robot.FieldBalance, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Robot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(robot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RobotUpsertOne) UpdateNewValues() *RobotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(robot.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(robot.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(robot.FieldTenantID)
		}
		if _, exists := u.create.mutation.Rid(); exists {
			s.SetIgnore(robot.FieldRid)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Robot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RobotUpsertOne) Ignore() *RobotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RobotUpsertOne) DoNothing() *RobotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RobotCreate.OnConflict
// documentation for more info.
func (u *RobotUpsertOne) Update(set func(*RobotUpsert)) *RobotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RobotUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *RobotUpsertOne) SetCreatedBy(v uint32) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RobotUpsertOne) AddCreatedBy(v uint32) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RobotUpsertOne) UpdateCreatedBy() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *RobotUpsertOne) ClearCreatedBy() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *RobotUpsertOne) SetUpdatedBy(v uint32) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *RobotUpsertOne) AddUpdatedBy(v uint32) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *RobotUpsertOne) UpdateUpdatedBy() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *RobotUpsertOne) ClearUpdatedBy() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *RobotUpsertOne) SetDeletedBy(v uint32) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *RobotUpsertOne) AddDeletedBy(v uint32) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *RobotUpsertOne) UpdateDeletedBy() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *RobotUpsertOne) ClearDeletedBy() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.ClearDeletedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RobotUpsertOne) SetUpdatedAt(v time.Time) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RobotUpsertOne) UpdateUpdatedAt() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *RobotUpsertOne) ClearUpdatedAt() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RobotUpsertOne) SetDeletedAt(v time.Time) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RobotUpsertOne) UpdateDeletedAt() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RobotUpsertOne) ClearDeletedAt() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.ClearDeletedAt()
	})
}

// SetRemark sets the "remark" field.
func (u *RobotUpsertOne) SetRemark(v string) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *RobotUpsertOne) UpdateRemark() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *RobotUpsertOne) ClearRemark() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.ClearRemark()
	})
}

// SetStatus sets the "status" field.
func (u *RobotUpsertOne) SetStatus(v uint) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *RobotUpsertOne) AddStatus(v uint) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RobotUpsertOne) UpdateStatus() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateStatus()
	})
}

// SetBalance sets the "balance" field.
func (u *RobotUpsertOne) SetBalance(v float64) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *RobotUpsertOne) AddBalance(v float64) *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *RobotUpsertOne) UpdateBalance() *RobotUpsertOne {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateBalance()
	})
}

// Exec executes the query.
func (u *RobotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RobotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RobotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RobotUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RobotUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RobotCreateBulk is the builder for creating many Robot entities in bulk.
type RobotCreateBulk struct {
	config
	err      error
	builders []*RobotCreate
	conflict []sql.ConflictOption
}

// Save creates the Robot entities in the database.
func (_c *RobotCreateBulk) Save(ctx context.Context) ([]*Robot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Robot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RobotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RobotCreateBulk) SaveX(ctx context.Context) []*Robot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RobotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RobotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Robot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RobotUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *RobotCreateBulk) OnConflict(opts ...sql.ConflictOption) *RobotUpsertBulk {
	_c.conflict = opts
	return &RobotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Robot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RobotCreateBulk) OnConflictColumns(columns ...string) *RobotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RobotUpsertBulk{
		create: _c,
	}
}

// RobotUpsertBulk is the builder for "upsert"-ing
// a bulk of Robot nodes.
type RobotUpsertBulk struct {
	create *RobotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Robot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(robot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RobotUpsertBulk) UpdateNewValues() *RobotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(robot.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(robot.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(robot.FieldTenantID)
			}
			if _, exists := b.mutation.Rid(); exists {
				s.SetIgnore(robot.FieldRid)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Robot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RobotUpsertBulk) Ignore() *RobotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RobotUpsertBulk) DoNothing() *RobotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RobotCreateBulk.OnConflict
// documentation for more info.
func (u *RobotUpsertBulk) Update(set func(*RobotUpsert)) *RobotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RobotUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *RobotUpsertBulk) SetCreatedBy(v uint32) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RobotUpsertBulk) AddCreatedBy(v uint32) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RobotUpsertBulk) UpdateCreatedBy() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *RobotUpsertBulk) ClearCreatedBy() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *RobotUpsertBulk) SetUpdatedBy(v uint32) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *RobotUpsertBulk) AddUpdatedBy(v uint32) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *RobotUpsertBulk) UpdateUpdatedBy() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *RobotUpsertBulk) ClearUpdatedBy() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *RobotUpsertBulk) SetDeletedBy(v uint32) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *RobotUpsertBulk) AddDeletedBy(v uint32) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *RobotUpsertBulk) UpdateDeletedBy() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *RobotUpsertBulk) ClearDeletedBy() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.ClearDeletedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RobotUpsertBulk) SetUpdatedAt(v time.Time) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RobotUpsertBulk) UpdateUpdatedAt() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *RobotUpsertBulk) ClearUpdatedAt() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RobotUpsertBulk) SetDeletedAt(v time.Time) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RobotUpsertBulk) UpdateDeletedAt() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RobotUpsertBulk) ClearDeletedAt() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.ClearDeletedAt()
	})
}

// SetRemark sets the "remark" field.
func (u *RobotUpsertBulk) SetRemark(v string) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *RobotUpsertBulk) UpdateRemark() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *RobotUpsertBulk) ClearRemark() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.ClearRemark()
	})
}

// SetStatus sets the "status" field.
func (u *RobotUpsertBulk) SetStatus(v uint) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *RobotUpsertBulk) AddStatus(v uint) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RobotUpsertBulk) UpdateStatus() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateStatus()
	})
}

// SetBalance sets the "balance" field.
func (u *RobotUpsertBulk) SetBalance(v float64) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *RobotUpsertBulk) AddBalance(v float64) *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *RobotUpsertBulk) UpdateBalance() *RobotUpsertBulk {
	return u.Update(func(s *RobotUpsert) {
		s.UpdateBalance()
	})
}

// Exec executes the query.
func (u *RobotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RobotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RobotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RobotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
