// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerCreate is the builder for creating a Server entity.
type ServerCreate struct {
	config
	mutation *ServerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ServerCreate) SetCreatedAt(v time.Time) *ServerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ServerCreate) SetNillableCreatedAt(v *time.Time) *ServerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ServerCreate) SetUpdatedAt(v time.Time) *ServerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ServerCreate) SetNillableUpdatedAt(v *time.Time) *ServerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ServerCreate) SetDeletedAt(v time.Time) *ServerCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ServerCreate) SetNillableDeletedAt(v *time.Time) *ServerCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ServerCreate) SetCreatedBy(v uint32) *ServerCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ServerCreate) SetNillableCreatedBy(v *uint32) *ServerCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ServerCreate) SetUpdatedBy(v uint32) *ServerCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ServerCreate) SetNillableUpdatedBy(v *uint32) *ServerCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *ServerCreate) SetDeletedBy(v uint32) *ServerCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *ServerCreate) SetNillableDeletedBy(v *uint32) *ServerCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *ServerCreate) SetNickname(v string) *ServerCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *ServerCreate) SetIP(v string) *ServerCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetInnerIP sets the "inner_ip" field.
func (_c *ServerCreate) SetInnerIP(v string) *ServerCreate {
	_c.mutation.SetInnerIP(v)
	return _c
}

// SetPort sets the "port" field.
func (_c *ServerCreate) SetPort(v string) *ServerCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetMachineID sets the "machine_id" field.
func (_c *ServerCreate) SetMachineID(v string) *ServerCreate {
	_c.mutation.SetMachineID(v)
	return _c
}

// SetNillableMachineID sets the "machine_id" field if the given value is not nil.
func (_c *ServerCreate) SetNillableMachineID(v *string) *ServerCreate {
	if v != nil {
		_c.SetMachineID(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *ServerCreate) SetRemark(v string) *ServerCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *ServerCreate) SetNillableRemark(v *string) *ServerCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetVpcID sets the "vpc_id" field.
func (_c *ServerCreate) SetVpcID(v string) *ServerCreate {
	_c.mutation.SetVpcID(v)
	return _c
}

// SetNillableVpcID sets the "vpc_id" field if the given value is not nil.
func (_c *ServerCreate) SetNillableVpcID(v *string) *ServerCreate {
	if v != nil {
		_c.SetVpcID(*v)
	}
	return _c
}

// SetInstanceID sets the "instance_id" field.
func (_c *ServerCreate) SetInstanceID(v string) *ServerCreate {
	_c.mutation.SetInstanceID(v)
	return _c
}

// SetNillableInstanceID sets the "instance_id" field if the given value is not nil.
func (_c *ServerCreate) SetNillableInstanceID(v *string) *ServerCreate {
	if v != nil {
		_c.SetInstanceID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ServerCreate) SetType(v int8) *ServerCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ServerCreate) SetNillableType(v *int8) *ServerCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetServerInfo sets the "server_info" field.
func (_c *ServerCreate) SetServerInfo(v map[string]interface{}) *ServerCreate {
	_c.mutation.SetServerInfo(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ServerCreate) SetID(v uint32) *ServerCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ServerMutation object of the builder.
func (_c *ServerCreate) Mutation() *ServerMutation {
	return _c.mutation
}

// Save creates the Server in the database.
func (_c *ServerCreate) Save(ctx context.Context) (*Server, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ServerCreate) SaveX(ctx context.Context) *Server {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ServerCreate) defaults() {
	if _, ok := _c.mutation.MachineID(); !ok {
		v := server.DefaultMachineID
		_c.mutation.SetMachineID(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := server.DefaultRemark
		_c.mutation.SetRemark(v)
	}
	if _, ok := _c.mutation.VpcID(); !ok {
		v := server.DefaultVpcID
		_c.mutation.SetVpcID(v)
	}
	if _, ok := _c.mutation.InstanceID(); !ok {
		v := server.DefaultInstanceID
		_c.mutation.SetInstanceID(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := server.DefaultType
		_c.mutation.SetType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ServerCreate) check() error {
	if _, ok := _c.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "Server.nickname"`)}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := server.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "Server.nickname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Server.ip"`)}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := server.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Server.ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InnerIP(); !ok {
		return &ValidationError{Name: "inner_ip", err: errors.New(`ent: missing required field "Server.inner_ip"`)}
	}
	if v, ok := _c.mutation.InnerIP(); ok {
		if err := server.InnerIPValidator(v); err != nil {
			return &ValidationError{Name: "inner_ip", err: fmt.Errorf(`ent: validator failed for field "Server.inner_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "Server.port"`)}
	}
	if v, ok := _c.mutation.Port(); ok {
		if err := server.PortValidator(v); err != nil {
			return &ValidationError{Name: "port", err: fmt.Errorf(`ent: validator failed for field "Server.port": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MachineID(); ok {
		if err := server.MachineIDValidator(v); err != nil {
			return &ValidationError{Name: "machine_id", err: fmt.Errorf(`ent: validator failed for field "Server.machine_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := server.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Server.remark": %w`, err)}
		}
	}
	if v, ok := _c.mutation.VpcID(); ok {
		if err := server.VpcIDValidator(v); err != nil {
			return &ValidationError{Name: "vpc_id", err: fmt.Errorf(`ent: validator failed for field "Server.vpc_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.InstanceID(); ok {
		if err := server.InstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "instance_id", err: fmt.Errorf(`ent: validator failed for field "Server.instance_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Server.type"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := server.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Server.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ServerCreate) sqlSave(ctx context.Context) (*Server, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ServerCreate) createSpec() (*Server, *sqlgraph.CreateSpec) {
	var (
		_node = &Server{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(server.Table, sqlgraph.NewFieldSpec(server.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(server.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(server.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(server.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(server.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(server.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(server.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(server.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(server.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.InnerIP(); ok {
		_spec.SetField(server.FieldInnerIP, field.TypeString, value)
		_node.InnerIP = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(server.FieldPort, field.TypeString, value)
		_node.Port = value
	}
	if value, ok := _c.mutation.MachineID(); ok {
		_spec.SetField(server.FieldMachineID, field.TypeString, value)
		_node.MachineID = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(server.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.VpcID(); ok {
		_spec.SetField(server.FieldVpcID, field.TypeString, value)
		_node.VpcID = &value
	}
	if value, ok := _c.mutation.InstanceID(); ok {
		_spec.SetField(server.FieldInstanceID, field.TypeString, value)
		_node.InstanceID = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(server.FieldType, field.TypeInt8, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.ServerInfo(); ok {
		_spec.SetField(server.FieldServerInfo, field.TypeJSON, value)
		_node.ServerInfo = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Server.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ServerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ServerCreate) OnConflict(opts ...sql.ConflictOption) *ServerUpsertOne {
	_c.conflict = opts
	return &ServerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Server.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ServerCreate) OnConflictColumns(columns ...string) *ServerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ServerUpsertOne{
		create: _c,
	}
}

type (
	// ServerUpsertOne is the builder for "upsert"-ing
	//  one Server node.
	ServerUpsertOne struct {
		create *ServerCreate
	}

	// ServerUpsert is the "OnConflict" setter.
	ServerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ServerUpsert) SetUpdatedAt(v time.Time) *ServerUpsert {
	u.Set(server.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ServerUpsert) UpdateUpdatedAt() *ServerUpsert {
	u.SetExcluded(server.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ServerUpsert) ClearUpdatedAt() *ServerUpsert {
	u.SetNull(server.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ServerUpsert) SetDeletedAt(v time.Time) *ServerUpsert {
	u.Set(server.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ServerUpsert) UpdateDeletedAt() *ServerUpsert {
	u.SetExcluded(server.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ServerUpsert) ClearDeletedAt() *ServerUpsert {
	u.SetNull(server.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ServerUpsert) SetCreatedBy(v uint32) *ServerUpsert {
	u.Set(server.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ServerUpsert) UpdateCreatedBy() *ServerUpsert {
	u.SetExcluded(server.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ServerUpsert) AddCreatedBy(v uint32) *ServerUpsert {
	u.Add(server.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ServerUpsert) ClearCreatedBy() *ServerUpsert {
	u.SetNull(server.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ServerUpsert) SetUpdatedBy(v uint32) *ServerUpsert {
	u.Set(server.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ServerUpsert) UpdateUpdatedBy() *ServerUpsert {
	u.SetExcluded(server.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ServerUpsert) AddUpdatedBy(v uint32) *ServerUpsert {
	u.Add(server.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ServerUpsert) ClearUpdatedBy() *ServerUpsert {
	u.SetNull(server.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ServerUpsert) SetDeletedBy(v uint32) *ServerUpsert {
	u.Set(server.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ServerUpsert) UpdateDeletedBy() *ServerUpsert {
	u.SetExcluded(server.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ServerUpsert) AddDeletedBy(v uint32) *ServerUpsert {
	u.Add(server.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ServerUpsert) ClearDeletedBy() *ServerUpsert {
	u.SetNull(server.FieldDeletedBy)
	return u
}

// SetNickname sets the "nickname" field.
func (u *ServerUpsert) SetNickname(v string) *ServerUpsert {
	u.Set(server.FieldNickname, v)
	return u
}

// UpdateNickname sets the "nickname" field to the value that was provided on create.
func (u *ServerUpsert) UpdateNickname() *ServerUpsert {
	u.SetExcluded(server.FieldNickname)
	return u
}

// SetIP sets the "ip" field.
func (u *ServerUpsert) SetIP(v string) *ServerUpsert {
	u.Set(server.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *ServerUpsert) UpdateIP() *ServerUpsert {
	u.SetExcluded(server.FieldIP)
	return u
}

// SetInnerIP sets the "inner_ip" field.
func (u *ServerUpsert) SetInnerIP(v string) *ServerUpsert {
	u.Set(server.FieldInnerIP, v)
	return u
}

// UpdateInnerIP sets the "inner_ip" field to the value that was provided on create.
func (u *ServerUpsert) UpdateInnerIP() *ServerUpsert {
	u.SetExcluded(server.FieldInnerIP)
	return u
}

// SetPort sets the "port" field.
func (u *ServerUpsert) SetPort(v string) *ServerUpsert {
	u.Set(server.FieldPort, v)
	return u
}

// UpdatePort sets the "port" field to the value that was provided on create.
func (u *ServerUpsert) UpdatePort() *ServerUpsert {
	u.SetExcluded(server.FieldPort)
	return u
}

// SetMachineID sets the "machine_id" field.
func (u *ServerUpsert) SetMachineID(v string) *ServerUpsert {
	u.Set(server.FieldMachineID, v)
	return u
}

// UpdateMachineID sets the "machine_id" field to the value that was provided on create.
func (u *ServerUpsert) UpdateMachineID() *ServerUpsert {
	u.SetExcluded(server.FieldMachineID)
	return u
}

// ClearMachineID clears the value of the "machine_id" field.
func (u *ServerUpsert) ClearMachineID() *ServerUpsert {
	u.SetNull(server.FieldMachineID)
	return u
}

// SetRemark sets the "remark" field.
func (u *ServerUpsert) SetRemark(v string) *ServerUpsert {
	u.Set(server.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ServerUpsert) UpdateRemark() *ServerUpsert {
	u.SetExcluded(server.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *ServerUpsert) ClearRemark() *ServerUpsert {
	u.SetNull(server.FieldRemark)
	return u
}

// SetVpcID sets the "vpc_id" field.
func (u *ServerUpsert) SetVpcID(v string) *ServerUpsert {
	u.Set(server.FieldVpcID, v)
	return u
}

// UpdateVpcID sets the "vpc_id" field to the value that was provided on create.
func (u *ServerUpsert) UpdateVpcID() *ServerUpsert {
	u.SetExcluded(server.FieldVpcID)
	return u
}

// ClearVpcID clears the value of the "vpc_id" field.
func (u *ServerUpsert) ClearVpcID() *ServerUpsert {
	u.SetNull(server.FieldVpcID)
	return u
}

// SetInstanceID sets the "instance_id" field.
func (u *ServerUpsert) SetInstanceID(v string) *ServerUpsert {
	u.Set(server.FieldInstanceID, v)
	return u
}

// UpdateInstanceID sets the "instance_id" field to the value that was provided on create.
func (u *ServerUpsert) UpdateInstanceID() *ServerUpsert {
	u.SetExcluded(server.FieldInstanceID)
	return u
}

// ClearInstanceID clears the value of the "instance_id" field.
func (u *ServerUpsert) ClearInstanceID() *ServerUpsert {
	u.SetNull(server.FieldInstanceID)
	return u
}

// SetType sets the "type" field.
func (u *ServerUpsert) SetType(v int8) *ServerUpsert {
	u.Set(server.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ServerUpsert) UpdateType() *ServerUpsert {
	u.SetExcluded(server.FieldType)
	return u
}

// AddType adds v to the "type" field.
func (u *ServerUpsert) AddType(v int8) *ServerUpsert {
	u.Add(server.FieldType, v)
	return u
}

// SetServerInfo sets the "server_info" field.
func (u *ServerUpsert) SetServerInfo(v map[string]interface{}) *ServerUpsert {
	u.Set(server.FieldServerInfo, v)
	return u
}

// UpdateServerInfo sets the "server_info" field to the value that was provided on create.
func (u *ServerUpsert) UpdateServerInfo() *ServerUpsert {
	u.SetExcluded(server.FieldServerInfo)
	return u
}

// ClearServerInfo clears the value of the "server_info" field.
func (u *ServerUpsert) ClearServerInfo() *ServerUpsert {
	u.SetNull(server.FieldServerInfo)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Server.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(server.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ServerUpsertOne) UpdateNewValues() *ServerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(server.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(server.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Server.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ServerUpsertOne) Ignore() *ServerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ServerUpsertOne) DoNothing() *ServerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ServerCreate.OnConflict
// documentation for more info.
func (u *ServerUpsertOne) Update(set func(*ServerUpsert)) *ServerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ServerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ServerUpsertOne) SetUpdatedAt(v time.Time) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateUpdatedAt() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ServerUpsertOne) ClearUpdatedAt() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ServerUpsertOne) SetDeletedAt(v time.Time) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateDeletedAt() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ServerUpsertOne) ClearDeletedAt() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ServerUpsertOne) SetCreatedBy(v uint32) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ServerUpsertOne) AddCreatedBy(v uint32) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateCreatedBy() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ServerUpsertOne) ClearCreatedBy() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ServerUpsertOne) SetUpdatedBy(v uint32) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ServerUpsertOne) AddUpdatedBy(v uint32) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateUpdatedBy() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ServerUpsertOne) ClearUpdatedBy() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ServerUpsertOne) SetDeletedBy(v uint32) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ServerUpsertOne) AddDeletedBy(v uint32) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateDeletedBy() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ServerUpsertOne) ClearDeletedBy() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearDeletedBy()
	})
}

// SetNickname sets the "nickname" field.
func (u *ServerUpsertOne) SetNickname(v string) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetNickname(v)
	})
}

// UpdateNickname sets the "nickname" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateNickname() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateNickname()
	})
}

// SetIP sets the "ip" field.
func (u *ServerUpsertOne) SetIP(v string) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateIP() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateIP()
	})
}

// SetInnerIP sets the "inner_ip" field.
func (u *ServerUpsertOne) SetInnerIP(v string) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetInnerIP(v)
	})
}

// UpdateInnerIP sets the "inner_ip" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateInnerIP() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateInnerIP()
	})
}

// SetPort sets the "port" field.
func (u *ServerUpsertOne) SetPort(v string) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetPort(v)
	})
}

// UpdatePort sets the "port" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdatePort() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdatePort()
	})
}

// SetMachineID sets the "machine_id" field.
func (u *ServerUpsertOne) SetMachineID(v string) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetMachineID(v)
	})
}

// UpdateMachineID sets the "machine_id" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateMachineID() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateMachineID()
	})
}

// ClearMachineID clears the value of the "machine_id" field.
func (u *ServerUpsertOne) ClearMachineID() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearMachineID()
	})
}

// SetRemark sets the "remark" field.
func (u *ServerUpsertOne) SetRemark(v string) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateRemark() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ServerUpsertOne) ClearRemark() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearRemark()
	})
}

// SetVpcID sets the "vpc_id" field.
func (u *ServerUpsertOne) SetVpcID(v string) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetVpcID(v)
	})
}

// UpdateVpcID sets the "vpc_id" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateVpcID() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateVpcID()
	})
}

// ClearVpcID clears the value of the "vpc_id" field.
func (u *ServerUpsertOne) ClearVpcID() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearVpcID()
	})
}

// SetInstanceID sets the "instance_id" field.
func (u *ServerUpsertOne) SetInstanceID(v string) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetInstanceID(v)
	})
}

// UpdateInstanceID sets the "instance_id" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateInstanceID() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateInstanceID()
	})
}

// ClearInstanceID clears the value of the "instance_id" field.
func (u *ServerUpsertOne) ClearInstanceID() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearInstanceID()
	})
}

// SetType sets the "type" field.
func (u *ServerUpsertOne) SetType(v int8) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *ServerUpsertOne) AddType(v int8) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateType() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateType()
	})
}

// SetServerInfo sets the "server_info" field.
func (u *ServerUpsertOne) SetServerInfo(v map[string]interface{}) *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.SetServerInfo(v)
	})
}

// UpdateServerInfo sets the "server_info" field to the value that was provided on create.
func (u *ServerUpsertOne) UpdateServerInfo() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateServerInfo()
	})
}

// ClearServerInfo clears the value of the "server_info" field.
func (u *ServerUpsertOne) ClearServerInfo() *ServerUpsertOne {
	return u.Update(func(s *ServerUpsert) {
		s.ClearServerInfo()
	})
}

// Exec executes the query.
func (u *ServerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ServerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ServerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ServerUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ServerUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ServerCreateBulk is the builder for creating many Server entities in bulk.
type ServerCreateBulk struct {
	config
	err      error
	builders []*ServerCreate
	conflict []sql.ConflictOption
}

// Save creates the Server entities in the database.
func (_c *ServerCreateBulk) Save(ctx context.Context) ([]*Server, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Server, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ServerCreateBulk) SaveX(ctx context.Context) []*Server {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Server.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ServerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ServerCreateBulk) OnConflict(opts ...sql.ConflictOption) *ServerUpsertBulk {
	_c.conflict = opts
	return &ServerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Server.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ServerCreateBulk) OnConflictColumns(columns ...string) *ServerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ServerUpsertBulk{
		create: _c,
	}
}

// ServerUpsertBulk is the builder for "upsert"-ing
// a bulk of Server nodes.
type ServerUpsertBulk struct {
	create *ServerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Server.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(server.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ServerUpsertBulk) UpdateNewValues() *ServerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(server.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(server.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Server.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ServerUpsertBulk) Ignore() *ServerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ServerUpsertBulk) DoNothing() *ServerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ServerCreateBulk.OnConflict
// documentation for more info.
func (u *ServerUpsertBulk) Update(set func(*ServerUpsert)) *ServerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ServerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ServerUpsertBulk) SetUpdatedAt(v time.Time) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateUpdatedAt() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ServerUpsertBulk) ClearUpdatedAt() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ServerUpsertBulk) SetDeletedAt(v time.Time) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateDeletedAt() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ServerUpsertBulk) ClearDeletedAt() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ServerUpsertBulk) SetCreatedBy(v uint32) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ServerUpsertBulk) AddCreatedBy(v uint32) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateCreatedBy() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ServerUpsertBulk) ClearCreatedBy() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ServerUpsertBulk) SetUpdatedBy(v uint32) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ServerUpsertBulk) AddUpdatedBy(v uint32) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateUpdatedBy() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ServerUpsertBulk) ClearUpdatedBy() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ServerUpsertBulk) SetDeletedBy(v uint32) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ServerUpsertBulk) AddDeletedBy(v uint32) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateDeletedBy() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ServerUpsertBulk) ClearDeletedBy() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearDeletedBy()
	})
}

// SetNickname sets the "nickname" field.
func (u *ServerUpsertBulk) SetNickname(v string) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetNickname(v)
	})
}

// UpdateNickname sets the "nickname" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateNickname() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateNickname()
	})
}

// SetIP sets the "ip" field.
func (u *ServerUpsertBulk) SetIP(v string) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateIP() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateIP()
	})
}

// SetInnerIP sets the "inner_ip" field.
func (u *ServerUpsertBulk) SetInnerIP(v string) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetInnerIP(v)
	})
}

// UpdateInnerIP sets the "inner_ip" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateInnerIP() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateInnerIP()
	})
}

// SetPort sets the "port" field.
func (u *ServerUpsertBulk) SetPort(v string) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetPort(v)
	})
}

// UpdatePort sets the "port" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdatePort() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdatePort()
	})
}

// SetMachineID sets the "machine_id" field.
func (u *ServerUpsertBulk) SetMachineID(v string) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetMachineID(v)
	})
}

// UpdateMachineID sets the "machine_id" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateMachineID() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateMachineID()
	})
}

// ClearMachineID clears the value of the "machine_id" field.
func (u *ServerUpsertBulk) ClearMachineID() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearMachineID()
	})
}

// SetRemark sets the "remark" field.
func (u *ServerUpsertBulk) SetRemark(v string) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateRemark() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *ServerUpsertBulk) ClearRemark() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearRemark()
	})
}

// SetVpcID sets the "vpc_id" field.
func (u *ServerUpsertBulk) SetVpcID(v string) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetVpcID(v)
	})
}

// UpdateVpcID sets the "vpc_id" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateVpcID() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateVpcID()
	})
}

// ClearVpcID clears the value of the "vpc_id" field.
func (u *ServerUpsertBulk) ClearVpcID() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearVpcID()
	})
}

// SetInstanceID sets the "instance_id" field.
func (u *ServerUpsertBulk) SetInstanceID(v string) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetInstanceID(v)
	})
}

// UpdateInstanceID sets the "instance_id" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateInstanceID() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateInstanceID()
	})
}

// ClearInstanceID clears the value of the "instance_id" field.
func (u *ServerUpsertBulk) ClearInstanceID() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearInstanceID()
	})
}

// SetType sets the "type" field.
func (u *ServerUpsertBulk) SetType(v int8) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *ServerUpsertBulk) AddType(v int8) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateType() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateType()
	})
}

// SetServerInfo sets the "server_info" field.
func (u *ServerUpsertBulk) SetServerInfo(v map[string]interface{}) *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.SetServerInfo(v)
	})
}

// UpdateServerInfo sets the "server_info" field to the value that was provided on create.
func (u *ServerUpsertBulk) UpdateServerInfo() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.UpdateServerInfo()
	})
}

// ClearServerInfo clears the value of the "server_info" field.
func (u *ServerUpsertBulk) ClearServerInfo() *ServerUpsertBulk {
	return u.Update(func(s *ServerUpsert) {
		s.ClearServerInfo()
	})
}

// Exec executes the query.
func (u *ServerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ServerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ServerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ServerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
