// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"go-wind-admin/app/admin/service/internal/data/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerUpdate is the builder for updating Server entities.
type ServerUpdate struct {
	config
	hooks     []Hook
	mutation  *ServerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ServerUpdate builder.
func (_u *ServerUpdate) Where(ps ...predicate.Server) *ServerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServerUpdate) SetUpdatedAt(v time.Time) *ServerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableUpdatedAt(v *time.Time) *ServerUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ServerUpdate) ClearUpdatedAt() *ServerUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ServerUpdate) SetDeletedAt(v time.Time) *ServerUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableDeletedAt(v *time.Time) *ServerUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ServerUpdate) ClearDeletedAt() *ServerUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ServerUpdate) SetCreatedBy(v uint32) *ServerUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableCreatedBy(v *uint32) *ServerUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ServerUpdate) AddCreatedBy(v int32) *ServerUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ServerUpdate) ClearCreatedBy() *ServerUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ServerUpdate) SetUpdatedBy(v uint32) *ServerUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableUpdatedBy(v *uint32) *ServerUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ServerUpdate) AddUpdatedBy(v int32) *ServerUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ServerUpdate) ClearUpdatedBy() *ServerUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ServerUpdate) SetDeletedBy(v uint32) *ServerUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableDeletedBy(v *uint32) *ServerUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ServerUpdate) AddDeletedBy(v int32) *ServerUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ServerUpdate) ClearDeletedBy() *ServerUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *ServerUpdate) SetNickname(v string) *ServerUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableNickname(v *string) *ServerUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *ServerUpdate) SetIP(v string) *ServerUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableIP(v *string) *ServerUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetInnerIP sets the "inner_ip" field.
func (_u *ServerUpdate) SetInnerIP(v string) *ServerUpdate {
	_u.mutation.SetInnerIP(v)
	return _u
}

// SetNillableInnerIP sets the "inner_ip" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableInnerIP(v *string) *ServerUpdate {
	if v != nil {
		_u.SetInnerIP(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ServerUpdate) SetPort(v string) *ServerUpdate {
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ServerUpdate) SetNillablePort(v *string) *ServerUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// SetMachineID sets the "machine_id" field.
func (_u *ServerUpdate) SetMachineID(v string) *ServerUpdate {
	_u.mutation.SetMachineID(v)
	return _u
}

// SetNillableMachineID sets the "machine_id" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableMachineID(v *string) *ServerUpdate {
	if v != nil {
		_u.SetMachineID(*v)
	}
	return _u
}

// ClearMachineID clears the value of the "machine_id" field.
func (_u *ServerUpdate) ClearMachineID() *ServerUpdate {
	_u.mutation.ClearMachineID()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ServerUpdate) SetRemark(v string) *ServerUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableRemark(v *string) *ServerUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ServerUpdate) ClearRemark() *ServerUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetVpcID sets the "vpc_id" field.
func (_u *ServerUpdate) SetVpcID(v string) *ServerUpdate {
	_u.mutation.SetVpcID(v)
	return _u
}

// SetNillableVpcID sets the "vpc_id" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableVpcID(v *string) *ServerUpdate {
	if v != nil {
		_u.SetVpcID(*v)
	}
	return _u
}

// ClearVpcID clears the value of the "vpc_id" field.
func (_u *ServerUpdate) ClearVpcID() *ServerUpdate {
	_u.mutation.ClearVpcID()
	return _u
}

// SetInstanceID sets the "instance_id" field.
func (_u *ServerUpdate) SetInstanceID(v string) *ServerUpdate {
	_u.mutation.SetInstanceID(v)
	return _u
}

// SetNillableInstanceID sets the "instance_id" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableInstanceID(v *string) *ServerUpdate {
	if v != nil {
		_u.SetInstanceID(*v)
	}
	return _u
}

// ClearInstanceID clears the value of the "instance_id" field.
func (_u *ServerUpdate) ClearInstanceID() *ServerUpdate {
	_u.mutation.ClearInstanceID()
	return _u
}

// SetType sets the "type" field.
func (_u *ServerUpdate) SetType(v int8) *ServerUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableType(v *int8) *ServerUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *ServerUpdate) AddType(v int8) *ServerUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetServerInfo sets the "server_info" field.
func (_u *ServerUpdate) SetServerInfo(v map[string]interface{}) *ServerUpdate {
	_u.mutation.SetServerInfo(v)
	return _u
}

// ClearServerInfo clears the value of the "server_info" field.
func (_u *ServerUpdate) ClearServerInfo() *ServerUpdate {
	_u.mutation.ClearServerInfo()
	return _u
}

// Mutation returns the ServerMutation object of the builder.
func (_u *ServerUpdate) Mutation() *ServerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServerUpdate) check() error {
	if v, ok := _u.mutation.Nickname(); ok {
		if err := server.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "Server.nickname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := server.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Server.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InnerIP(); ok {
		if err := server.InnerIPValidator(v); err != nil {
			return &ValidationError{Name: "inner_ip", err: fmt.Errorf(`ent: validator failed for field "Server.inner_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Port(); ok {
		if err := server.PortValidator(v); err != nil {
			return &ValidationError{Name: "port", err: fmt.Errorf(`ent: validator failed for field "Server.port": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MachineID(); ok {
		if err := server.MachineIDValidator(v); err != nil {
			return &ValidationError{Name: "machine_id", err: fmt.Errorf(`ent: validator failed for field "Server.machine_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := server.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Server.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VpcID(); ok {
		if err := server.VpcIDValidator(v); err != nil {
			return &ValidationError{Name: "vpc_id", err: fmt.Errorf(`ent: validator failed for field "Server.vpc_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InstanceID(); ok {
		if err := server.InstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "instance_id", err: fmt.Errorf(`ent: validator failed for field "Server.instance_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ServerUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ServerUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ServerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(server.Table, server.Columns, sqlgraph.NewFieldSpec(server.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(server.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(server.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(server.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(server.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(server.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(server.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(server.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(server.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(server.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(server.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(server.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(server.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(server.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(server.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(server.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(server.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.InnerIP(); ok {
		_spec.SetField(server.FieldInnerIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(server.FieldPort, field.TypeString, value)
	}
	if value, ok := _u.mutation.MachineID(); ok {
		_spec.SetField(server.FieldMachineID, field.TypeString, value)
	}
	if _u.mutation.MachineIDCleared() {
		_spec.ClearField(server.FieldMachineID, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(server.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(server.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.VpcID(); ok {
		_spec.SetField(server.FieldVpcID, field.TypeString, value)
	}
	if _u.mutation.VpcIDCleared() {
		_spec.ClearField(server.FieldVpcID, field.TypeString)
	}
	if value, ok := _u.mutation.InstanceID(); ok {
		_spec.SetField(server.FieldInstanceID, field.TypeString, value)
	}
	if _u.mutation.InstanceIDCleared() {
		_spec.ClearField(server.FieldInstanceID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(server.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(server.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ServerInfo(); ok {
		_spec.SetField(server.FieldServerInfo, field.TypeJSON, value)
	}
	if _u.mutation.ServerInfoCleared() {
		_spec.ClearField(server.FieldServerInfo, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{server.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServerUpdateOne is the builder for updating a single Server entity.
type ServerUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ServerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServerUpdateOne) SetUpdatedAt(v time.Time) *ServerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableUpdatedAt(v *time.Time) *ServerUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ServerUpdateOne) ClearUpdatedAt() *ServerUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ServerUpdateOne) SetDeletedAt(v time.Time) *ServerUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableDeletedAt(v *time.Time) *ServerUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ServerUpdateOne) ClearDeletedAt() *ServerUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ServerUpdateOne) SetCreatedBy(v uint32) *ServerUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableCreatedBy(v *uint32) *ServerUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ServerUpdateOne) AddCreatedBy(v int32) *ServerUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ServerUpdateOne) ClearCreatedBy() *ServerUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ServerUpdateOne) SetUpdatedBy(v uint32) *ServerUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableUpdatedBy(v *uint32) *ServerUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ServerUpdateOne) AddUpdatedBy(v int32) *ServerUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ServerUpdateOne) ClearUpdatedBy() *ServerUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ServerUpdateOne) SetDeletedBy(v uint32) *ServerUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableDeletedBy(v *uint32) *ServerUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ServerUpdateOne) AddDeletedBy(v int32) *ServerUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ServerUpdateOne) ClearDeletedBy() *ServerUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *ServerUpdateOne) SetNickname(v string) *ServerUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableNickname(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *ServerUpdateOne) SetIP(v string) *ServerUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableIP(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetInnerIP sets the "inner_ip" field.
func (_u *ServerUpdateOne) SetInnerIP(v string) *ServerUpdateOne {
	_u.mutation.SetInnerIP(v)
	return _u
}

// SetNillableInnerIP sets the "inner_ip" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableInnerIP(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetInnerIP(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ServerUpdateOne) SetPort(v string) *ServerUpdateOne {
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillablePort(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// SetMachineID sets the "machine_id" field.
func (_u *ServerUpdateOne) SetMachineID(v string) *ServerUpdateOne {
	_u.mutation.SetMachineID(v)
	return _u
}

// SetNillableMachineID sets the "machine_id" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableMachineID(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetMachineID(*v)
	}
	return _u
}

// ClearMachineID clears the value of the "machine_id" field.
func (_u *ServerUpdateOne) ClearMachineID() *ServerUpdateOne {
	_u.mutation.ClearMachineID()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ServerUpdateOne) SetRemark(v string) *ServerUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableRemark(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ServerUpdateOne) ClearRemark() *ServerUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetVpcID sets the "vpc_id" field.
func (_u *ServerUpdateOne) SetVpcID(v string) *ServerUpdateOne {
	_u.mutation.SetVpcID(v)
	return _u
}

// SetNillableVpcID sets the "vpc_id" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableVpcID(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetVpcID(*v)
	}
	return _u
}

// ClearVpcID clears the value of the "vpc_id" field.
func (_u *ServerUpdateOne) ClearVpcID() *ServerUpdateOne {
	_u.mutation.ClearVpcID()
	return _u
}

// SetInstanceID sets the "instance_id" field.
func (_u *ServerUpdateOne) SetInstanceID(v string) *ServerUpdateOne {
	_u.mutation.SetInstanceID(v)
	return _u
}

// SetNillableInstanceID sets the "instance_id" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableInstanceID(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetInstanceID(*v)
	}
	return _u
}

// ClearInstanceID clears the value of the "instance_id" field.
func (_u *ServerUpdateOne) ClearInstanceID() *ServerUpdateOne {
	_u.mutation.ClearInstanceID()
	return _u
}

// SetType sets the "type" field.
func (_u *ServerUpdateOne) SetType(v int8) *ServerUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableType(v *int8) *ServerUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *ServerUpdateOne) AddType(v int8) *ServerUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetServerInfo sets the "server_info" field.
func (_u *ServerUpdateOne) SetServerInfo(v map[string]interface{}) *ServerUpdateOne {
	_u.mutation.SetServerInfo(v)
	return _u
}

// ClearServerInfo clears the value of the "server_info" field.
func (_u *ServerUpdateOne) ClearServerInfo() *ServerUpdateOne {
	_u.mutation.ClearServerInfo()
	return _u
}

// Mutation returns the ServerMutation object of the builder.
func (_u *ServerUpdateOne) Mutation() *ServerMutation {
	return _u.mutation
}

// Where appends a list predicates to the ServerUpdate builder.
func (_u *ServerUpdateOne) Where(ps ...predicate.Server) *ServerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServerUpdateOne) Select(field string, fields ...string) *ServerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Server entity.
func (_u *ServerUpdateOne) Save(ctx context.Context) (*Server, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerUpdateOne) SaveX(ctx context.Context) *Server {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServerUpdateOne) check() error {
	if v, ok := _u.mutation.Nickname(); ok {
		if err := server.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "Server.nickname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := server.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Server.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InnerIP(); ok {
		if err := server.InnerIPValidator(v); err != nil {
			return &ValidationError{Name: "inner_ip", err: fmt.Errorf(`ent: validator failed for field "Server.inner_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Port(); ok {
		if err := server.PortValidator(v); err != nil {
			return &ValidationError{Name: "port", err: fmt.Errorf(`ent: validator failed for field "Server.port": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MachineID(); ok {
		if err := server.MachineIDValidator(v); err != nil {
			return &ValidationError{Name: "machine_id", err: fmt.Errorf(`ent: validator failed for field "Server.machine_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := server.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Server.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VpcID(); ok {
		if err := server.VpcIDValidator(v); err != nil {
			return &ValidationError{Name: "vpc_id", err: fmt.Errorf(`ent: validator failed for field "Server.vpc_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InstanceID(); ok {
		if err := server.InstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "instance_id", err: fmt.Errorf(`ent: validator failed for field "Server.instance_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ServerUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ServerUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ServerUpdateOne) sqlSave(ctx context.Context) (_node *Server, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(server.Table, server.Columns, sqlgraph.NewFieldSpec(server.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Server.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, server.FieldID)
		for _, f := range fields {
			if !server.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != server.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(server.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(server.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(server.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(server.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(server.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(server.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(server.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(server.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(server.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(server.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(server.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(server.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(server.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(server.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(server.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(server.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.InnerIP(); ok {
		_spec.SetField(server.FieldInnerIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(server.FieldPort, field.TypeString, value)
	}
	if value, ok := _u.mutation.MachineID(); ok {
		_spec.SetField(server.FieldMachineID, field.TypeString, value)
	}
	if _u.mutation.MachineIDCleared() {
		_spec.ClearField(server.FieldMachineID, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(server.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(server.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.VpcID(); ok {
		_spec.SetField(server.FieldVpcID, field.TypeString, value)
	}
	if _u.mutation.VpcIDCleared() {
		_spec.ClearField(server.FieldVpcID, field.TypeString)
	}
	if value, ok := _u.mutation.InstanceID(); ok {
		_spec.SetField(server.FieldInstanceID, field.TypeString, value)
	}
	if _u.mutation.InstanceIDCleared() {
		_spec.ClearField(server.FieldInstanceID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(server.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(server.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ServerInfo(); ok {
		_spec.SetField(server.FieldServerInfo, field.TypeJSON, value)
	}
	if _u.mutation.ServerInfoCleared() {
		_spec.ClearField(server.FieldServerInfo, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Server{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{server.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
