// Code generated by ent, DO NOT EDIT.

package server

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the server type in the database.
	Label = "server"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldInnerIP holds the string denoting the inner_ip field in the database.
	FieldInnerIP = "inner_ip"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldMachineID holds the string denoting the machine_id field in the database.
	FieldMachineID = "machine_id"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldVpcID holds the string denoting the vpc_id field in the database.
	FieldVpcID = "vpc_id"
	// FieldInstanceID holds the string denoting the instance_id field in the database.
	FieldInstanceID = "instance_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldServerInfo holds the string denoting the server_info field in the database.
	FieldServerInfo = "server_info"
	// Table holds the table name of the server in the database.
	Table = "trading_servers"
)

// Columns holds all SQL columns for server fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldNickname,
	FieldIP,
	FieldInnerIP,
	FieldPort,
	FieldMachineID,
	FieldRemark,
	FieldVpcID,
	FieldInstanceID,
	FieldType,
	FieldServerInfo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	NicknameValidator func(string) error
	// IPValidator is a validator for the "ip" field. It is called by the builders before save.
	IPValidator func(string) error
	// InnerIPValidator is a validator for the "inner_ip" field. It is called by the builders before save.
	InnerIPValidator func(string) error
	// PortValidator is a validator for the "port" field. It is called by the builders before save.
	PortValidator func(string) error
	// DefaultMachineID holds the default value on creation for the "machine_id" field.
	DefaultMachineID string
	// MachineIDValidator is a validator for the "machine_id" field. It is called by the builders before save.
	MachineIDValidator func(string) error
	// DefaultRemark holds the default value on creation for the "remark" field.
	DefaultRemark string
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// DefaultVpcID holds the default value on creation for the "vpc_id" field.
	DefaultVpcID string
	// VpcIDValidator is a validator for the "vpc_id" field. It is called by the builders before save.
	VpcIDValidator func(string) error
	// DefaultInstanceID holds the default value on creation for the "instance_id" field.
	DefaultInstanceID string
	// InstanceIDValidator is a validator for the "instance_id" field. It is called by the builders before save.
	InstanceIDValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType int8
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// OrderOption defines the ordering options for the Server queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByInnerIP orders the results by the inner_ip field.
func ByInnerIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInnerIP, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByMachineID orders the results by the machine_id field.
func ByMachineID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMachineID, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByVpcID orders the results by the vpc_id field.
func ByVpcID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVpcID, opts...).ToFunc()
}

// ByInstanceID orders the results by the instance_id field.
func ByInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstanceID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}
