// Code generated by ent, DO NOT EDIT.

package server

import (
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldDeletedBy, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldNickname, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldIP, v))
}

// InnerIP applies equality check predicate on the "inner_ip" field. It's identical to InnerIPEQ.
func InnerIP(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldInnerIP, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldPort, v))
}

// MachineID applies equality check predicate on the "machine_id" field. It's identical to MachineIDEQ.
func MachineID(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldMachineID, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldRemark, v))
}

// VpcID applies equality check predicate on the "vpc_id" field. It's identical to VpcIDEQ.
func VpcID(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldVpcID, v))
}

// InstanceID applies equality check predicate on the "instance_id" field. It's identical to InstanceIDEQ.
func InstanceID(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldInstanceID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v int8) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldDeletedBy))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.Server {
	return predicate.Server(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.Server {
	return predicate.Server(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.Server {
	return predicate.Server(sql.FieldContainsFold(FieldNickname, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.Server {
	return predicate.Server(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.Server {
	return predicate.Server(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.Server {
	return predicate.Server(sql.FieldContainsFold(FieldIP, v))
}

// InnerIPEQ applies the EQ predicate on the "inner_ip" field.
func InnerIPEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldInnerIP, v))
}

// InnerIPNEQ applies the NEQ predicate on the "inner_ip" field.
func InnerIPNEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldInnerIP, v))
}

// InnerIPIn applies the In predicate on the "inner_ip" field.
func InnerIPIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldInnerIP, vs...))
}

// InnerIPNotIn applies the NotIn predicate on the "inner_ip" field.
func InnerIPNotIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldInnerIP, vs...))
}

// InnerIPGT applies the GT predicate on the "inner_ip" field.
func InnerIPGT(v string) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldInnerIP, v))
}

// InnerIPGTE applies the GTE predicate on the "inner_ip" field.
func InnerIPGTE(v string) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldInnerIP, v))
}

// InnerIPLT applies the LT predicate on the "inner_ip" field.
func InnerIPLT(v string) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldInnerIP, v))
}

// InnerIPLTE applies the LTE predicate on the "inner_ip" field.
func InnerIPLTE(v string) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldInnerIP, v))
}

// InnerIPContains applies the Contains predicate on the "inner_ip" field.
func InnerIPContains(v string) predicate.Server {
	return predicate.Server(sql.FieldContains(FieldInnerIP, v))
}

// InnerIPHasPrefix applies the HasPrefix predicate on the "inner_ip" field.
func InnerIPHasPrefix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasPrefix(FieldInnerIP, v))
}

// InnerIPHasSuffix applies the HasSuffix predicate on the "inner_ip" field.
func InnerIPHasSuffix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasSuffix(FieldInnerIP, v))
}

// InnerIPEqualFold applies the EqualFold predicate on the "inner_ip" field.
func InnerIPEqualFold(v string) predicate.Server {
	return predicate.Server(sql.FieldEqualFold(FieldInnerIP, v))
}

// InnerIPContainsFold applies the ContainsFold predicate on the "inner_ip" field.
func InnerIPContainsFold(v string) predicate.Server {
	return predicate.Server(sql.FieldContainsFold(FieldInnerIP, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v string) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v string) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v string) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v string) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldPort, v))
}

// PortContains applies the Contains predicate on the "port" field.
func PortContains(v string) predicate.Server {
	return predicate.Server(sql.FieldContains(FieldPort, v))
}

// PortHasPrefix applies the HasPrefix predicate on the "port" field.
func PortHasPrefix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasPrefix(FieldPort, v))
}

// PortHasSuffix applies the HasSuffix predicate on the "port" field.
func PortHasSuffix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasSuffix(FieldPort, v))
}

// PortEqualFold applies the EqualFold predicate on the "port" field.
func PortEqualFold(v string) predicate.Server {
	return predicate.Server(sql.FieldEqualFold(FieldPort, v))
}

// PortContainsFold applies the ContainsFold predicate on the "port" field.
func PortContainsFold(v string) predicate.Server {
	return predicate.Server(sql.FieldContainsFold(FieldPort, v))
}

// MachineIDEQ applies the EQ predicate on the "machine_id" field.
func MachineIDEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldMachineID, v))
}

// MachineIDNEQ applies the NEQ predicate on the "machine_id" field.
func MachineIDNEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldMachineID, v))
}

// MachineIDIn applies the In predicate on the "machine_id" field.
func MachineIDIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldMachineID, vs...))
}

// MachineIDNotIn applies the NotIn predicate on the "machine_id" field.
func MachineIDNotIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldMachineID, vs...))
}

// MachineIDGT applies the GT predicate on the "machine_id" field.
func MachineIDGT(v string) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldMachineID, v))
}

// MachineIDGTE applies the GTE predicate on the "machine_id" field.
func MachineIDGTE(v string) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldMachineID, v))
}

// MachineIDLT applies the LT predicate on the "machine_id" field.
func MachineIDLT(v string) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldMachineID, v))
}

// MachineIDLTE applies the LTE predicate on the "machine_id" field.
func MachineIDLTE(v string) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldMachineID, v))
}

// MachineIDContains applies the Contains predicate on the "machine_id" field.
func MachineIDContains(v string) predicate.Server {
	return predicate.Server(sql.FieldContains(FieldMachineID, v))
}

// MachineIDHasPrefix applies the HasPrefix predicate on the "machine_id" field.
func MachineIDHasPrefix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasPrefix(FieldMachineID, v))
}

// MachineIDHasSuffix applies the HasSuffix predicate on the "machine_id" field.
func MachineIDHasSuffix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasSuffix(FieldMachineID, v))
}

// MachineIDIsNil applies the IsNil predicate on the "machine_id" field.
func MachineIDIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldMachineID))
}

// MachineIDNotNil applies the NotNil predicate on the "machine_id" field.
func MachineIDNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldMachineID))
}

// MachineIDEqualFold applies the EqualFold predicate on the "machine_id" field.
func MachineIDEqualFold(v string) predicate.Server {
	return predicate.Server(sql.FieldEqualFold(FieldMachineID, v))
}

// MachineIDContainsFold applies the ContainsFold predicate on the "machine_id" field.
func MachineIDContainsFold(v string) predicate.Server {
	return predicate.Server(sql.FieldContainsFold(FieldMachineID, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Server {
	return predicate.Server(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Server {
	return predicate.Server(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Server {
	return predicate.Server(sql.FieldContainsFold(FieldRemark, v))
}

// VpcIDEQ applies the EQ predicate on the "vpc_id" field.
func VpcIDEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldVpcID, v))
}

// VpcIDNEQ applies the NEQ predicate on the "vpc_id" field.
func VpcIDNEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldVpcID, v))
}

// VpcIDIn applies the In predicate on the "vpc_id" field.
func VpcIDIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldVpcID, vs...))
}

// VpcIDNotIn applies the NotIn predicate on the "vpc_id" field.
func VpcIDNotIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldVpcID, vs...))
}

// VpcIDGT applies the GT predicate on the "vpc_id" field.
func VpcIDGT(v string) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldVpcID, v))
}

// VpcIDGTE applies the GTE predicate on the "vpc_id" field.
func VpcIDGTE(v string) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldVpcID, v))
}

// VpcIDLT applies the LT predicate on the "vpc_id" field.
func VpcIDLT(v string) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldVpcID, v))
}

// VpcIDLTE applies the LTE predicate on the "vpc_id" field.
func VpcIDLTE(v string) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldVpcID, v))
}

// VpcIDContains applies the Contains predicate on the "vpc_id" field.
func VpcIDContains(v string) predicate.Server {
	return predicate.Server(sql.FieldContains(FieldVpcID, v))
}

// VpcIDHasPrefix applies the HasPrefix predicate on the "vpc_id" field.
func VpcIDHasPrefix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasPrefix(FieldVpcID, v))
}

// VpcIDHasSuffix applies the HasSuffix predicate on the "vpc_id" field.
func VpcIDHasSuffix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasSuffix(FieldVpcID, v))
}

// VpcIDIsNil applies the IsNil predicate on the "vpc_id" field.
func VpcIDIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldVpcID))
}

// VpcIDNotNil applies the NotNil predicate on the "vpc_id" field.
func VpcIDNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldVpcID))
}

// VpcIDEqualFold applies the EqualFold predicate on the "vpc_id" field.
func VpcIDEqualFold(v string) predicate.Server {
	return predicate.Server(sql.FieldEqualFold(FieldVpcID, v))
}

// VpcIDContainsFold applies the ContainsFold predicate on the "vpc_id" field.
func VpcIDContainsFold(v string) predicate.Server {
	return predicate.Server(sql.FieldContainsFold(FieldVpcID, v))
}

// InstanceIDEQ applies the EQ predicate on the "instance_id" field.
func InstanceIDEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldInstanceID, v))
}

// InstanceIDNEQ applies the NEQ predicate on the "instance_id" field.
func InstanceIDNEQ(v string) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldInstanceID, v))
}

// InstanceIDIn applies the In predicate on the "instance_id" field.
func InstanceIDIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldInstanceID, vs...))
}

// InstanceIDNotIn applies the NotIn predicate on the "instance_id" field.
func InstanceIDNotIn(vs ...string) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldInstanceID, vs...))
}

// InstanceIDGT applies the GT predicate on the "instance_id" field.
func InstanceIDGT(v string) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldInstanceID, v))
}

// InstanceIDGTE applies the GTE predicate on the "instance_id" field.
func InstanceIDGTE(v string) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldInstanceID, v))
}

// InstanceIDLT applies the LT predicate on the "instance_id" field.
func InstanceIDLT(v string) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldInstanceID, v))
}

// InstanceIDLTE applies the LTE predicate on the "instance_id" field.
func InstanceIDLTE(v string) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldInstanceID, v))
}

// InstanceIDContains applies the Contains predicate on the "instance_id" field.
func InstanceIDContains(v string) predicate.Server {
	return predicate.Server(sql.FieldContains(FieldInstanceID, v))
}

// InstanceIDHasPrefix applies the HasPrefix predicate on the "instance_id" field.
func InstanceIDHasPrefix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasPrefix(FieldInstanceID, v))
}

// InstanceIDHasSuffix applies the HasSuffix predicate on the "instance_id" field.
func InstanceIDHasSuffix(v string) predicate.Server {
	return predicate.Server(sql.FieldHasSuffix(FieldInstanceID, v))
}

// InstanceIDIsNil applies the IsNil predicate on the "instance_id" field.
func InstanceIDIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldInstanceID))
}

// InstanceIDNotNil applies the NotNil predicate on the "instance_id" field.
func InstanceIDNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldInstanceID))
}

// InstanceIDEqualFold applies the EqualFold predicate on the "instance_id" field.
func InstanceIDEqualFold(v string) predicate.Server {
	return predicate.Server(sql.FieldEqualFold(FieldInstanceID, v))
}

// InstanceIDContainsFold applies the ContainsFold predicate on the "instance_id" field.
func InstanceIDContainsFold(v string) predicate.Server {
	return predicate.Server(sql.FieldContainsFold(FieldInstanceID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v int8) predicate.Server {
	return predicate.Server(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v int8) predicate.Server {
	return predicate.Server(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...int8) predicate.Server {
	return predicate.Server(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...int8) predicate.Server {
	return predicate.Server(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v int8) predicate.Server {
	return predicate.Server(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v int8) predicate.Server {
	return predicate.Server(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v int8) predicate.Server {
	return predicate.Server(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v int8) predicate.Server {
	return predicate.Server(sql.FieldLTE(FieldType, v))
}

// ServerInfoIsNil applies the IsNil predicate on the "server_info" field.
func ServerInfoIsNil() predicate.Server {
	return predicate.Server(sql.FieldIsNull(FieldServerInfo))
}

// ServerInfoNotNil applies the NotNil predicate on the "server_info" field.
func ServerInfoNotNil() predicate.Server {
	return predicate.Server(sql.FieldNotNull(FieldServerInfo))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Server) predicate.Server {
	return predicate.Server(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Server) predicate.Server {
	return predicate.Server(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Server) predicate.Server {
	return predicate.Server(sql.NotPredicates(p))
}
