// Code generated by ent, DO NOT EDIT.

package exchangeaccount

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the exchangeaccount type in the database.
	Label = "exchange_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldExchangeName holds the string denoting the exchange_name field in the database.
	FieldExchangeName = "exchange_name"
	// FieldOriginAccount holds the string denoting the origin_account field in the database.
	FieldOriginAccount = "origin_account"
	// FieldAPIKey holds the string denoting the api_key field in the database.
	FieldAPIKey = "api_key"
	// FieldSecretKey holds the string denoting the secret_key field in the database.
	FieldSecretKey = "secret_key"
	// FieldPassKey holds the string denoting the pass_key field in the database.
	FieldPassKey = "pass_key"
	// FieldBrokerID holds the string denoting the broker_id field in the database.
	FieldBrokerID = "broker_id"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldServerIps holds the string denoting the server_ips field in the database.
	FieldServerIps = "server_ips"
	// FieldSpecialReqLimit holds the string denoting the special_req_limit field in the database.
	FieldSpecialReqLimit = "special_req_limit"
	// FieldAccountType holds the string denoting the account_type field in the database.
	FieldAccountType = "account_type"
	// FieldApplyTime holds the string denoting the apply_time field in the database.
	FieldApplyTime = "apply_time"
	// FieldIsCombined holds the string denoting the is_combined field in the database.
	FieldIsCombined = "is_combined"
	// FieldIsMulti holds the string denoting the is_multi field in the database.
	FieldIsMulti = "is_multi"
	// FieldAccountIds holds the string denoting the account_ids field in the database.
	FieldAccountIds = "account_ids"
	// FieldMotherID holds the string denoting the mother_id field in the database.
	FieldMotherID = "mother_id"
	// Table holds the table name of the exchangeaccount in the database.
	Table = "trading_exchange_accounts"
)

// Columns holds all SQL columns for exchangeaccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldNickname,
	FieldExchangeName,
	FieldOriginAccount,
	FieldAPIKey,
	FieldSecretKey,
	FieldPassKey,
	FieldBrokerID,
	FieldRemark,
	FieldServerIps,
	FieldSpecialReqLimit,
	FieldAccountType,
	FieldApplyTime,
	FieldIsCombined,
	FieldIsMulti,
	FieldAccountIds,
	FieldMotherID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	NicknameValidator func(string) error
	// ExchangeNameValidator is a validator for the "exchange_name" field. It is called by the builders before save.
	ExchangeNameValidator func(string) error
	// OriginAccountValidator is a validator for the "origin_account" field. It is called by the builders before save.
	OriginAccountValidator func(string) error
	// APIKeyValidator is a validator for the "api_key" field. It is called by the builders before save.
	APIKeyValidator func(string) error
	// SecretKeyValidator is a validator for the "secret_key" field. It is called by the builders before save.
	SecretKeyValidator func(string) error
	// DefaultPassKey holds the default value on creation for the "pass_key" field.
	DefaultPassKey string
	// PassKeyValidator is a validator for the "pass_key" field. It is called by the builders before save.
	PassKeyValidator func(string) error
	// DefaultBrokerID holds the default value on creation for the "broker_id" field.
	DefaultBrokerID string
	// BrokerIDValidator is a validator for the "broker_id" field. It is called by the builders before save.
	BrokerIDValidator func(string) error
	// DefaultRemark holds the default value on creation for the "remark" field.
	DefaultRemark string
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// DefaultServerIps holds the default value on creation for the "server_ips" field.
	DefaultServerIps string
	// DefaultSpecialReqLimit holds the default value on creation for the "special_req_limit" field.
	DefaultSpecialReqLimit float64
	// DefaultAccountType holds the default value on creation for the "account_type" field.
	DefaultAccountType int8
	// DefaultApplyTime holds the default value on creation for the "apply_time" field.
	DefaultApplyTime int64
	// DefaultIsCombined holds the default value on creation for the "is_combined" field.
	DefaultIsCombined bool
	// DefaultIsMulti holds the default value on creation for the "is_multi" field.
	DefaultIsMulti bool
	// DefaultMotherID holds the default value on creation for the "mother_id" field.
	DefaultMotherID uint32
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// OrderOption defines the ordering options for the ExchangeAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByExchangeName orders the results by the exchange_name field.
func ByExchangeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeName, opts...).ToFunc()
}

// ByOriginAccount orders the results by the origin_account field.
func ByOriginAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginAccount, opts...).ToFunc()
}

// ByAPIKey orders the results by the api_key field.
func ByAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKey, opts...).ToFunc()
}

// BySecretKey orders the results by the secret_key field.
func BySecretKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretKey, opts...).ToFunc()
}

// ByPassKey orders the results by the pass_key field.
func ByPassKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassKey, opts...).ToFunc()
}

// ByBrokerID orders the results by the broker_id field.
func ByBrokerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrokerID, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByServerIps orders the results by the server_ips field.
func ByServerIps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerIps, opts...).ToFunc()
}

// BySpecialReqLimit orders the results by the special_req_limit field.
func BySpecialReqLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpecialReqLimit, opts...).ToFunc()
}

// ByAccountType orders the results by the account_type field.
func ByAccountType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountType, opts...).ToFunc()
}

// ByApplyTime orders the results by the apply_time field.
func ByApplyTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplyTime, opts...).ToFunc()
}

// ByIsCombined orders the results by the is_combined field.
func ByIsCombined(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCombined, opts...).ToFunc()
}

// ByIsMulti orders the results by the is_multi field.
func ByIsMulti(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsMulti, opts...).ToFunc()
}

// ByMotherID orders the results by the mother_id field.
func ByMotherID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMotherID, opts...).ToFunc()
}
