// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package helper

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper(in *jlexer.Lexer, out *Signal) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "t":
			out.Time = int64(in.Int64())
		case "T":
			out.Type = SignalType(in.Int())
		case "C":
			out.ClientID = string(in.String())
		case "O":
			out.OrderID = string(in.String())
		case "p":
			out.Price = float64(in.Float64())
		case "a":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Amount).UnmarshalJSON(data))
			}
		case "os":
			out.OrderSide = OrderSide(in.Int())
		case "ot":
			out.OrderType = OrderType(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper(out *jwriter.Writer, in Signal) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Time != 0 {
		const prefix string = ",\"t\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	if in.Type != 0 {
		const prefix string = ",\"T\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Type))
	}
	if in.ClientID != "" {
		const prefix string = ",\"C\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ClientID))
	}
	if in.OrderID != "" {
		const prefix string = ",\"O\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.OrderID))
	}
	if in.Price != 0 {
		const prefix string = ",\"p\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Price))
	}
	if true {
		const prefix string = ",\"a\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Amount).MarshalJSON())
	}
	if in.OrderSide != 0 {
		const prefix string = ",\"os\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.OrderSide))
	}
	if in.OrderType != 0 {
		const prefix string = ",\"ot\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.OrderType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Signal) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Signal) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Signal) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Signal) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper(l, v)
}
func easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelperSeq(in *jlexer.Lexer, out *Seq_T) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "e":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Ex).UnmarshalJSON(data))
			}
		case "i":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Inner).UnmarshalJSON(data))
			}
		case "ii":
			out.InnerServerId = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelperSeq(out *jwriter.Writer, in Seq_T) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"e\":"
		out.RawString(prefix[1:])
		out.Raw((in.Ex).MarshalJSON())
	}
	{
		const prefix string = ",\"i\":"
		out.RawString(prefix)
		out.Raw((in.Inner).MarshalJSON())
	}
	{
		const prefix string = ",\"ii\":"
		out.RawString(prefix)
		out.Int64(int64(in.InnerServerId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Seq_T) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelperSeq(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Seq_T) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelperSeq(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Seq_T) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelperSeq(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Seq_T) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelperSeq(l, v)
}
func easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper1(in *jlexer.Lexer, out *Pos) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "S":
			(out.Seq).UnmarshalEasyJSON(in)
		case "tm":
			out.Time = int64(in.Int64())
		case "p":
			(out.Pair).UnmarshalEasyJSON(in)
		case "l":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.LongPos).UnmarshalJSON(data))
			}
		case "la":
			out.LongAvg = float64(in.Float64())
		case "lv":
			out.LongValue = float64(in.Float64())
		case "s":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ShortPos).UnmarshalJSON(data))
			}
		case "sa":
			out.ShortAvg = float64(in.Float64())
		case "sv":
			out.ShortValue = float64(in.Float64())
		case "t":
			out.TradeNum = int64(in.Int64())
		case "T":
			out.TradeVol = float64(in.Float64())
		case "P":
			out.Profit = float64(in.Float64())
		case "aht":
			out.AHT = int64(in.Int64())
		case "ots":
			out.OpenTs = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper1(out *jwriter.Writer, in Pos) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"S\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Seq).MarshalEasyJSON(out)
	}
	if in.Time != 0 {
		const prefix string = ",\"tm\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	if true {
		const prefix string = ",\"p\":"
		out.RawString(prefix)
		(in.Pair).MarshalEasyJSON(out)
	}
	if true {
		const prefix string = ",\"l\":"
		out.RawString(prefix)
		out.Raw((in.LongPos).MarshalJSON())
	}
	if in.LongAvg != 0 {
		const prefix string = ",\"la\":"
		out.RawString(prefix)
		out.Float64(float64(in.LongAvg))
	}
	if in.LongValue != 0 {
		const prefix string = ",\"lv\":"
		out.RawString(prefix)
		out.Float64(float64(in.LongValue))
	}
	if true {
		const prefix string = ",\"s\":"
		out.RawString(prefix)
		out.Raw((in.ShortPos).MarshalJSON())
	}
	if in.ShortAvg != 0 {
		const prefix string = ",\"sa\":"
		out.RawString(prefix)
		out.Float64(float64(in.ShortAvg))
	}
	if in.ShortValue != 0 {
		const prefix string = ",\"sv\":"
		out.RawString(prefix)
		out.Float64(float64(in.ShortValue))
	}
	if in.TradeNum != 0 {
		const prefix string = ",\"t\":"
		out.RawString(prefix)
		out.Int64(int64(in.TradeNum))
	}
	if in.TradeVol != 0 {
		const prefix string = ",\"T\":"
		out.RawString(prefix)
		out.Float64(float64(in.TradeVol))
	}
	if in.Profit != 0 {
		const prefix string = ",\"P\":"
		out.RawString(prefix)
		out.Float64(float64(in.Profit))
	}
	if in.AHT != 0 {
		const prefix string = ",\"aht\":"
		out.RawString(prefix)
		out.Int64(int64(in.AHT))
	}
	if in.OpenTs != 0 {
		const prefix string = ",\"ots\":"
		out.RawString(prefix)
		out.Int64(int64(in.OpenTs))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Pos) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Pos) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Pos) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Pos) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper1(l, v)
}
func easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper2(in *jlexer.Lexer, out *Pair) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "b":
			out.Base = string(in.String())
		case "q":
			out.Quote = string(in.String())
		case "m":
			out.More = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper2(out *jwriter.Writer, in Pair) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Base != "" {
		const prefix string = ",\"b\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Base))
	}
	if in.Quote != "" {
		const prefix string = ",\"q\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Quote))
	}
	if in.More != "" {
		const prefix string = ",\"m\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.More))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Pair) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Pair) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Pair) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Pair) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper2(l, v)
}
func easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper3(in *jlexer.Lexer, out *OrderEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "I":
			out.ID = int64(in.Int64())
		case "t":
			out.Type = OrderEventType(in.Int())
		case "C":
			out.ClientID = string(in.String())
		case "O":
			out.OrderID = string(in.String())
		case "fp":
			out.FilledPrice = float64(in.Float64())
		case "ot":
			out.OrderType = OrderType(in.Int())
		case "os":
			out.OrderSide = OrderSide(in.Int())
		case "f":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Filled).UnmarshalJSON(data))
			}
		case "c":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CashFee).UnmarshalJSON(data))
			}
		case "cf":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CoinFee).UnmarshalJSON(data))
			}
		case "er":
			out.ErrorReason = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper3(out *jwriter.Writer, in OrderEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"I\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	if in.Type != 0 {
		const prefix string = ",\"t\":"
		out.RawString(prefix)
		out.Int(int(in.Type))
	}
	if in.ClientID != "" {
		const prefix string = ",\"C\":"
		out.RawString(prefix)
		out.String(string(in.ClientID))
	}
	if in.OrderID != "" {
		const prefix string = ",\"O\":"
		out.RawString(prefix)
		out.String(string(in.OrderID))
	}
	if in.FilledPrice != 0 {
		const prefix string = ",\"fp\":"
		out.RawString(prefix)
		out.Float64(float64(in.FilledPrice))
	}
	if in.OrderType != 0 {
		const prefix string = ",\"ot\":"
		out.RawString(prefix)
		out.Int(int(in.OrderType))
	}
	if in.OrderSide != 0 {
		const prefix string = ",\"os\":"
		out.RawString(prefix)
		out.Int(int(in.OrderSide))
	}
	if true {
		const prefix string = ",\"f\":"
		out.RawString(prefix)
		out.Raw((in.Filled).MarshalJSON())
	}
	if true {
		const prefix string = ",\"c\":"
		out.RawString(prefix)
		out.Raw((in.CashFee).MarshalJSON())
	}
	if true {
		const prefix string = ",\"cf\":"
		out.RawString(prefix)
		out.Raw((in.CoinFee).MarshalJSON())
	}
	if in.ErrorReason != "" {
		const prefix string = ",\"er\":"
		out.RawString(prefix)
		out.String(string(in.ErrorReason))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper3(l, v)
}
func easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper4(in *jlexer.Lexer, out *Equity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "S":
			(out.Seq).UnmarshalEasyJSON(in)
		case "CP":
			out.CoinPrice = float64(in.Float64())
		case "C":
			out.Coin = float64(in.Float64())
		case "CF":
			out.CoinFree = float64(in.Float64())
		case "c":
			out.Cash = float64(in.Float64())
		case "cf":
			out.CashFree = float64(in.Float64())
		case "cu":
			out.CashUpl = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper4(out *jwriter.Writer, in Equity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"S\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Seq).MarshalEasyJSON(out)
	}
	if in.CoinPrice != 0 {
		const prefix string = ",\"CP\":"
		out.RawString(prefix)
		out.Float64(float64(in.CoinPrice))
	}
	if in.Coin != 0 {
		const prefix string = ",\"C\":"
		out.RawString(prefix)
		out.Float64(float64(in.Coin))
	}
	if in.CoinFree != 0 {
		const prefix string = ",\"CF\":"
		out.RawString(prefix)
		out.Float64(float64(in.CoinFree))
	}
	if in.Cash != 0 {
		const prefix string = ",\"c\":"
		out.RawString(prefix)
		out.Float64(float64(in.Cash))
	}
	if in.CashFree != 0 {
		const prefix string = ",\"cf\":"
		out.RawString(prefix)
		out.Float64(float64(in.CashFree))
	}
	if in.CashUpl != 0 {
		const prefix string = ",\"cu\":"
		out.RawString(prefix)
		out.Float64(float64(in.CashUpl))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Equity) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Equity) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Equity) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Equity) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper4(l, v)
}
func easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper5(in *jlexer.Lexer, out *DepthItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "p":
			out.Price = float64(in.Float64())
		case "a":
			out.Amount = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper5(out *jwriter.Writer, in DepthItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"p\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"a\":"
		out.RawString(prefix)
		out.Float64(float64(in.Amount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DepthItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DepthItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DepthItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DepthItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper5(l, v)
}
func easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper6(in *jlexer.Lexer, out *Depth) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Seq":
			(out.Seq).UnmarshalEasyJSON(in)
		case "b":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([]DepthItem, 0, 4)
					} else {
						out.Bids = []DepthItem{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v1 DepthItem
					(v1).UnmarshalEasyJSON(in)
					out.Bids = append(out.Bids, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "a":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([]DepthItem, 0, 4)
					} else {
						out.Asks = []DepthItem{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v2 DepthItem
					(v2).UnmarshalEasyJSON(in)
					out.Asks = append(out.Asks, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper6(out *jwriter.Writer, in Depth) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Seq\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Seq).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"b\":"
		out.RawString(prefix)
		if in.Bids == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Bids {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"a\":"
		out.RawString(prefix)
		if in.Asks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Asks {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Depth) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Depth) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComThousandQuantBeastquantHelper6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Depth) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Depth) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComThousandQuantBeastquantHelper6(l, v)
}
